const express = require('express');
const { rateLimit } = require('express-rate-limit');
const controller = require('../controllers/public-content.controller');
const { publicContentResponses } = require('../contracts/public-content.responses');
const { responseContract } = require('../shared/http/response-contract');
const router = express.Router();
const limiter = rateLimit({ windowMs: 60_000, limit: 240, standardHeaders: 'draft-8', legacyHeaders: false, handler: (req, res) => res.status(429).json({ error: 'Too many public content requests.', code: 'PUBLIC_CONTENT_RATE_LIMITED', correlationId: req.context?.correlationId }) });
router.get('/content/:marketCode/:locale/:type/:slug', limiter, responseContract(publicContentResponses.content), controller.content);
router.get('/sitemap/:marketCode/:locale', limiter, responseContract(publicContentResponses.sitemap), controller.sitemap);
router.get('/redirect', limiter, responseContract(publicContentResponses.redirect), controller.redirect);
module.exports = router;
