import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS, RADIUS, SPACING } from '@/constants/theme';
import { useAuthStore } from '@/store/authStore';

export default function ProfileScreen() {
  const { user, profile, logout } = useAuthStore();
  const documents = profile?.documents ?? [];
  const approvedDocument = documents.some((document) => document.status === 'APPROVED');
  const verificationSteps = [
    { label: 'Datos de contacto', detail: 'Correo y teléfono registrados', complete: Boolean(user?.email && user?.phone) },
    { label: 'Documento de identidad', detail: 'Revisado por el equipo de seguridad', complete: approvedDocument },
    { label: 'Revisión profesional', detail: 'Perfil autorizado para aceptar trabajos', complete: profile?.status === 'APPROVED' },
  ];
  const completedSteps = verificationSteps.filter((step) => step.complete).length;
  const signOut = () => Alert.alert('Cerrar sesión', '¿Deseas salir de tu cuenta profesional?', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Cerrar sesión', style: 'destructive', onPress: async () => { await logout(); router.replace('/auth/login'); } }]);
  return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={styles.title}>Perfil profesional</Text>
    <View style={styles.card}><View style={styles.avatar}><Text style={styles.initials}>{user?.firstName?.[0]}{user?.lastName?.[0]}</Text></View><Text style={styles.name}>{user?.firstName} {user?.lastName}</Text><Text style={styles.email}>{user?.email}</Text><View style={styles.status}><Ionicons name={profile?.status === 'APPROVED' ? 'shield-checkmark' : 'time'} size={17} color={profile?.status === 'APPROVED' ? COLORS.success : COLORS.warning} /><Text style={[styles.statusText, { color: profile?.status === 'APPROVED' ? COLORS.success : COLORS.warning }]}>{profile?.status === 'APPROVED' ? 'Perfil verificado' : 'Verificación en curso'}</Text></View></View>
    <View style={styles.verificationCard}><View style={styles.verificationHeader}><View><Text style={styles.verificationTitle}>Verificación de la cuenta</Text><Text style={styles.verificationSubtitle}>{completedSteps} de {verificationSteps.length} pasos completados</Text></View><Text style={styles.progressText}>{Math.round((completedSteps / verificationSteps.length) * 100)}%</Text></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${(completedSteps / verificationSteps.length) * 100}%` }]} /></View>{verificationSteps.map((step) => <View key={step.label} style={styles.step}><Ionicons name={step.complete ? 'checkmark-circle' : 'ellipse-outline'} size={23} color={step.complete ? COLORS.success : COLORS.muted} /><View style={styles.stepText}><Text style={styles.stepLabel}>{step.label}</Text><Text style={styles.stepDetail}>{step.detail}</Text></View></View>)}{profile?.status !== 'APPROVED' && <View style={styles.notice}><Ionicons name="information-circle-outline" size={20} color={COLORS.primary} /><Text style={styles.noticeText}>Puedes consultar tu cuenta mientras revisamos los datos. Confirmar y completar trabajos se habilita al aprobar la verificación.</Text></View>}</View>
    <Pressable style={styles.logout} onPress={signOut}><Ionicons name="log-out-outline" size={21} color={COLORS.danger} /><Text style={styles.logoutText}>Cerrar sesión</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: COLORS.background }, content: { flexGrow: 1, padding: SPACING.lg, paddingBottom: SPACING.xxl }, title: { color: COLORS.text, fontSize: 27, fontWeight: '800', marginBottom: SPACING.xl }, card: { backgroundColor: COLORS.surface, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: COLORS.border, padding: SPACING.xl, alignItems: 'center' }, avatar: { width: 78, height: 78, borderRadius: RADIUS.full, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' }, initials: { color: COLORS.white, fontSize: 24, fontWeight: '800' }, name: { color: COLORS.text, fontSize: 21, fontWeight: '800', marginTop: SPACING.lg }, email: { color: COLORS.muted, marginTop: 4 }, status: { flexDirection: 'row', alignItems: 'center', gap: SPACING.xs, marginTop: SPACING.lg }, statusText: { fontSize: 13, fontWeight: '700' }, verificationCard: { backgroundColor: COLORS.surface, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: COLORS.border, padding: SPACING.lg, marginTop: SPACING.lg }, verificationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, verificationTitle: { color: COLORS.text, fontWeight: '800', fontSize: 17 }, verificationSubtitle: { color: COLORS.muted, fontSize: 12, marginTop: 3 }, progressText: { color: COLORS.primary, fontWeight: '800' }, progressTrack: { height: 7, borderRadius: RADIUS.full, backgroundColor: COLORS.border, overflow: 'hidden', marginVertical: SPACING.lg }, progressFill: { height: '100%', backgroundColor: COLORS.primary, borderRadius: RADIUS.full }, step: { flexDirection: 'row', alignItems: 'center', marginBottom: SPACING.md }, stepText: { flex: 1, marginLeft: SPACING.sm }, stepLabel: { color: COLORS.text, fontWeight: '700' }, stepDetail: { color: COLORS.muted, fontSize: 12, marginTop: 2 }, notice: { flexDirection: 'row', backgroundColor: '#EEF5FF', borderRadius: RADIUS.md, padding: SPACING.md, marginTop: SPACING.xs }, noticeText: { flex: 1, color: COLORS.text, fontSize: 12, lineHeight: 18, marginLeft: SPACING.sm }, logout: { minHeight: 54, borderRadius: RADIUS.md, backgroundColor: '#FEECEC', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: SPACING.sm, marginTop: SPACING.xl }, logoutText: { color: COLORS.danger, fontWeight: '700' } });
