import { useCallback, useEffect, useState } from 'react'
import { Alert, Pressable, RefreshControl, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { router } from 'expo-router'
import { SafeAreaView } from 'react-native-safe-area-context'
import { api, getApiError } from '@/services/api'
import { COLORS, RADIUS, SPACING } from '@/constants/theme'

type Program = { key: string; name: string; rewardType: string }
type Code = { id: string; code: string; status: string; useCount: number; maxUses: number; program: { name: string } }
type Referral = { id: string; status: string; riskStatus: string; program: { name: string }; rewards: Array<{ id: string; status: string; rewardType: string; amount?: string; currency?: string; benefitKey?: string }> }

export default function ProfessionalReferralsScreen() {
  const [programs, setPrograms] = useState<Program[]>([]); const [codes, setCodes] = useState<Code[]>([]); const [referrals, setReferrals] = useState<Referral[]>([]); const [claimCode, setClaimCode] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { const [p, c, r] = await Promise.all([api.referralPrograms(), api.referralCodes(), api.referrals()]); setPrograms(p.items); setCodes(c.items); setReferrals(r.items) } catch (error) { Alert.alert('Error', getApiError(error)) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const create = async (key: string) => { try { await api.createReferralCode(key); await load() } catch (error) { Alert.alert('Error', getApiError(error)) } }
  const claim = async () => { try { await api.claimReferral(claimCode); setClaimCode(''); await load(); Alert.alert('Código aplicado', 'La elegibilidad y el avance se verificarán con eventos autoritativos.') } catch (error) { Alert.alert('Error', getApiError(error)) } }
  return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={() => router.back()}><Ionicons name="arrow-back" size={25} color={COLORS.text} /></Pressable><Text style={s.title}>Invitaciones profesionales</Text><View style={{ width: 25 }} /></View><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />}>
    <Text style={s.explain}>Los programas de profesionales son independientes de los de clientes. El servidor valida mercado, identidad, eventos reales, límites y riesgo.</Text>
    <View style={s.card}><Text style={s.cardTitle}>Aplicar código</Text><TextInput accessibilityLabel="Código de invitación" autoCapitalize="characters" autoCorrect={false} maxLength={68} placeholder="REF_…" value={claimCode} onChangeText={setClaimCode} style={s.input} /><Pressable disabled={!/^REF_[A-Z0-9]{24,64}$/.test(claimCode.trim().toUpperCase())} style={[s.button, !claimCode && s.disabled]} onPress={claim}><Text style={s.buttonText}>Aplicar</Text></Pressable></View>
    <Text style={s.section}>Mis códigos</Text>{codes.map((item) => <View style={s.card} key={item.id}><View style={s.row}><View style={{ flex: 1 }}><Text style={s.cardTitle}>{item.program.name}</Text><Text selectable style={s.code}>{item.code}</Text><Text style={s.meta}>{item.status} · {item.useCount}/{item.maxUses}</Text></View>{item.status === 'ACTIVE' && <Pressable accessibilityLabel="Compartir código" onPress={() => Share.share({ message: `Invitación profesional ProApp: ${item.code}` })}><Ionicons name="share-social-outline" size={25} color={COLORS.primary} /></Pressable>}</View></View>)}
    {programs.filter((program) => !codes.some((code) => code.program.name === program.name && code.status === 'ACTIVE')).map((program) => <View style={s.card} key={program.key}><Text style={s.cardTitle}>{program.name}</Text><Text style={s.meta}>Beneficio: {program.rewardType}</Text><Pressable style={s.button} onPress={() => create(program.key)}><Text style={s.buttonText}>Crear código seguro</Text></Pressable></View>)}
    <Text style={s.section}>Estado y recompensas</Text>{referrals.length === 0 && <Text style={s.empty}>Aún no hay invitaciones profesionales.</Text>}{referrals.map((item) => <View style={s.card} key={item.id}><View style={s.row}><Text style={s.cardTitle}>{item.program.name}</Text><Text style={s.status}>{item.status}</Text></View><Text style={s.meta}>Revisión: {item.riskStatus}</Text>{item.rewards.map((reward) => <Text key={reward.id} style={s.reward}>{reward.rewardType}: {reward.amount ? `${reward.amount} ${reward.currency}` : reward.benefitKey} · {reward.status}</Text>)}</View>)}
  </ScrollView></SafeAreaView>
}

const s = StyleSheet.create({ safe:{flex:1,backgroundColor:COLORS.background},header:{height:60,paddingHorizontal:SPACING.lg,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:COLORS.border},title:{fontSize:19,fontWeight:'800',color:COLORS.text},content:{padding:SPACING.lg,paddingBottom:48},explain:{color:COLORS.muted,lineHeight:20,marginBottom:SPACING.lg},section:{fontWeight:'800',color:COLORS.text,fontSize:17,marginTop:SPACING.lg,marginBottom:SPACING.sm},card:{backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.lg,padding:SPACING.lg,marginBottom:SPACING.md},cardTitle:{fontWeight:'800',color:COLORS.text,fontSize:16},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:SPACING.md},input:{borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.md,padding:SPACING.md,marginVertical:SPACING.md,color:COLORS.text},button:{backgroundColor:COLORS.primary,borderRadius:RADIUS.md,minHeight:44,alignItems:'center',justifyContent:'center',paddingHorizontal:SPACING.lg,marginTop:SPACING.md},disabled:{opacity:.45},buttonText:{color:COLORS.white,fontWeight:'800'},code:{fontFamily:'monospace',color:COLORS.primary,marginTop:SPACING.sm},meta:{color:COLORS.muted,marginTop:SPACING.xs},status:{color:COLORS.primary,fontWeight:'800'},reward:{color:COLORS.text,marginTop:SPACING.sm},empty:{color:COLORS.muted,paddingVertical:SPACING.lg} })
