import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, type DivisionOption, type MarketSummary, type RegistrationSchema } from '@/services/api';
import { COLORS, RADIUS, SPACING } from '@/constants/theme';

type Area = { id: string; market: { code: string }; division: DivisionOption };

export default function ServiceAreasScreen() {
  const [markets, setMarkets] = useState<MarketSummary[]>([]); const [schema, setSchema] = useState<RegistrationSchema | null>(null); const [options, setOptions] = useState<Record<number, DivisionOption[]>>({}); const [selected, setSelected] = useState<Record<number, DivisionOption>>({}); const [areas, setAreas] = useState<Area[]>([]); const [error, setError] = useState('');
  const market = markets[0];
  const loadAreas = () => api.serviceAreas().then(({ items }) => setAreas(items as Area[])).catch((value) => setError(value instanceof Error ? value.message : 'No se pudieron cargar las áreas'));
  useEffect(() => { void loadAreas(); api.markets().then(({ items }) => setMarkets(items)).catch(() => setError('No hay mercados disponibles')); }, []);
  useEffect(() => { if (!market) return; api.registrationSchema(market.code).then(async (value) => { setSchema(value); setOptions({ 1: (await api.divisions(market.code)).items }); }).catch(() => setError('No se pudo cargar la política territorial')); }, [market]);
  const choose = async (level: number, division: DivisionOption) => { if (!schema || !market) return; const next = Object.fromEntries(Object.entries(selected).filter(([key]) => Number(key) < level)) as Record<number, DivisionOption>; next[level] = division; setSelected(next); if (level < schema.geography.levels.length) { const children = await api.divisions(market.code, division.id); setOptions((current) => ({ ...current, [level + 1]: children.items })); } };
  const add = async () => { if (!market || !schema) return; const leaf = selected[schema.geography.levels.length]; if (!leaf) return Alert.alert('Selecciona la cobertura', 'Completa la jerarquía hasta la división de servicio.'); try { await api.addServiceArea({ marketCode: market.code, schemaVersion: schema.schemaVersion, divisionId: leaf.id }); setSelected({}); await loadAreas(); } catch (value) { Alert.alert('No se pudo añadir', value instanceof Error ? value.message : 'Error'); } };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Volver</Text></Pressable><Text style={styles.title}>Áreas de servicio</Text><Text style={styles.subtitle}>La cobertura no se infiere del domicilio. F8.5 admite divisiones administrativas oficiales; radio y polígonos permanecen deshabilitados.</Text>{error && <View style={styles.notice}><Text>{error}</Text></View>}<View style={styles.card}><Text style={styles.heading}>Cobertura activa</Text>{areas.length === 0 ? <Text style={styles.muted}>Aún no hay áreas configuradas.</Text> : areas.map((area) => <View key={area.id} style={styles.row}><Text style={styles.bold}>{area.division.canonicalName}</Text><Text style={styles.muted}>{area.market.code} · {area.division.typeKey}</Text></View>)}</View>{schema && <View style={styles.card}><Text style={styles.heading}>Añadir división</Text>{schema.geography.levels.map((level) => <View key={level.level}><Text style={styles.label}>{level.type}</Text><View style={styles.options}>{(options[level.level] || []).map((division) => <Pressable key={division.id} onPress={() => void choose(level.level, division)} style={[styles.option, selected[level.level]?.id === division.id && styles.selected]}><Text>{division.canonicalName}</Text></Pressable>)}</View></View>)}<Pressable style={styles.button} onPress={() => void add()}><Text style={styles.buttonText}>Añadir área</Text></Pressable></View>}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:COLORS.background},content:{padding:SPACING.lg,paddingBottom:SPACING.xxl},back:{color:COLORS.primary,fontWeight:'700',marginBottom:SPACING.lg},title:{fontSize:28,fontWeight:'800',color:COLORS.text},subtitle:{color:COLORS.muted,lineHeight:21,marginVertical:SPACING.md},notice:{padding:SPACING.md,backgroundColor:'#FFF7E6',borderRadius:RADIUS.md},card:{backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,borderWidth:1,borderColor:COLORS.border,padding:SPACING.lg,marginTop:SPACING.lg},heading:{fontSize:18,fontWeight:'800',color:COLORS.text,marginBottom:SPACING.md},row:{paddingVertical:SPACING.sm,borderBottomWidth:1,borderBottomColor:COLORS.border},bold:{fontWeight:'700',color:COLORS.text},muted:{color:COLORS.muted,fontSize:12,marginTop:3},label:{fontWeight:'700',color:COLORS.text,marginBottom:SPACING.sm},options:{flexDirection:'row',flexWrap:'wrap',gap:SPACING.sm,marginBottom:SPACING.md},option:{padding:SPACING.sm,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.sm},selected:{borderColor:COLORS.primary,backgroundColor:'#EEF5FF'},button:{minHeight:50,backgroundColor:COLORS.primary,borderRadius:RADIUS.md,alignItems:'center',justifyContent:'center'},buttonText:{color:COLORS.white,fontWeight:'800'} });
