const PERMISSIONS = Object.freeze({
  DASHBOARD_READ: 'dashboard.read',
  PROFESSIONALS_REVIEW: 'professionals.review',
  AUDIT_READ: 'audit.read',
  USERS_READ: 'users.read',
  USERS_PII_READ: 'users.pii.read',
  USERS_MANAGE: 'users.manage',
  PROFESSIONALS_READ: 'professionals.read',
  PROFESSIONALS_MANAGE: 'professionals.manage',
  BOOKINGS_READ: 'bookings.read',
  PAYMENTS_READ: 'payments.read',
  REFUNDS_MANAGE: 'refunds.manage',
  PAYOUTS_MANAGE: 'payouts.manage',
  DISPUTES_READ: 'disputes.read',
  RECONCILIATION_RUN: 'reconciliation.run',
  MARKETING_MANAGE: 'marketing.manage',
  INCIDENTS_MANAGE: 'incidents.manage',
  SETTINGS_MANAGE: 'settings.manage',
  ROLES_MANAGE: 'roles.manage',
  ROLES_READ: 'roles.read',
  SESSIONS_MANAGE: 'sessions.manage',
  ANALYTICS_READ: 'analytics.read',
});

const ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: ['*'],
  OPERATIONS_ADMIN: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROFESSIONALS_REVIEW,
    PERMISSIONS.PROFESSIONALS_READ,
    PERMISSIONS.PROFESSIONALS_MANAGE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_PII_READ,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.BOOKINGS_READ,
    PERMISSIONS.INCIDENTS_MANAGE,
  ],
  MARKETING_ADMIN: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.MARKETING_MANAGE, PERMISSIONS.ANALYTICS_READ],
  FINANCE_ADMIN: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.REFUNDS_MANAGE,
    PERMISSIONS.PAYOUTS_MANAGE,
    PERMISSIONS.DISPUTES_READ,
    PERMISSIONS.RECONCILIATION_RUN,
    PERMISSIONS.ANALYTICS_READ,
  ],
  SUPPORT_ADMIN: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_PII_READ,
    PERMISSIONS.PROFESSIONALS_READ,
    PERMISSIONS.BOOKINGS_READ,
  ],
  COMPLIANCE_ADMIN: [
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_PII_READ,
    PERMISSIONS.PROFESSIONALS_READ,
    PERMISSIONS.PROFESSIONALS_REVIEW,
    PERMISSIONS.ROLES_READ,
  ],
  ANALYST: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.ANALYTICS_READ],
});

const roleGrantsPermission = (roleKey, permission) => {
  const grants = ROLE_PERMISSIONS[roleKey] || [];
  return grants.includes('*') || grants.includes(permission);
};

module.exports = { PERMISSIONS, ROLE_PERMISSIONS, roleGrantsPermission };
