const PERMISSIONS = Object.freeze({
  DASHBOARD_READ: 'dashboard.read',
  PROFESSIONALS_REVIEW: 'professionals.review',
  AUDIT_READ: 'audit.read',
  USERS_READ: 'users.read',
  BOOKINGS_READ: 'bookings.read',
  PAYMENTS_READ: 'payments.read',
  REFUNDS_MANAGE: 'refunds.manage',
  PAYOUTS_MANAGE: 'payouts.manage',
  MARKETING_MANAGE: 'marketing.manage',
  INCIDENTS_MANAGE: 'incidents.manage',
  SETTINGS_MANAGE: 'settings.manage',
  ROLES_MANAGE: 'roles.manage',
  ANALYTICS_READ: 'analytics.read',
});

const ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: ['*'],
  OPERATIONS_ADMIN: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROFESSIONALS_REVIEW,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.BOOKINGS_READ,
    PERMISSIONS.INCIDENTS_MANAGE,
  ],
  MARKETING_ADMIN: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.MARKETING_MANAGE, PERMISSIONS.ANALYTICS_READ],
  FINANCE_ADMIN: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.REFUNDS_MANAGE,
    PERMISSIONS.PAYOUTS_MANAGE,
    PERMISSIONS.ANALYTICS_READ,
  ],
  SUPPORT_ADMIN: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.USERS_READ, PERMISSIONS.BOOKINGS_READ],
  COMPLIANCE_ADMIN: [PERMISSIONS.AUDIT_READ, PERMISSIONS.USERS_READ, PERMISSIONS.PROFESSIONALS_REVIEW],
  ANALYST: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.ANALYTICS_READ],
});

const roleGrantsPermission = (roleKey, permission) => {
  const grants = ROLE_PERMISSIONS[roleKey] || [];
  return grants.includes('*') || grants.includes(permission);
};

module.exports = { PERMISSIONS, ROLE_PERMISSIONS, roleGrantsPermission };
