export default {
  common:{error:'Error',success:'Success',cancel:'Cancel',accept:'OK',save:'Save changes',loading:'Loading…',quantity:'Qty.',professional:'Professional',services:'Services',dateTime:'Date & time',location:'Location',payment:'Payment',notes:'Notes',notFound:'Not found',goBack:'Go back'},
  tabs:{home:'Home',search:'Search',bookings:'Bookings',profile:'Profile'},
  auth:{tagline:'Find trusted professionals for your home',email:'Email',emailPlaceholder:'Enter your email',password:'Password',passwordPlaceholder:'Enter your password',forgot:'Forgot password?',signIn:'Sign in',or:'OR',google:'Continue with Google',apple:'Continue with Apple',noAccount:"Don't have an account?",signUp:'Sign up',required:'Please fill in all fields',invalidEmail:'Please enter a valid email',createAccount:'Create account',registerSubtitle:'Enter your details to register',firstName:'First name',lastName:'Last name',phone:'Phone',confirmPassword:'Confirm password',register:'Register',hasAccount:'Already have an account?',passwordsMismatch:'Passwords do not match',passwordLength:'Password must be at least 8 characters'},
  home:{title:'Find professionals',subtitle:'Book trusted services for your home',top:'Top professionals',seeAll:'See all',empty:'No professionals found',defaultProfessional:'Professional',years:'{{count}} years',approved:'Approved',verified:'Verified',perHour:'/hour'},
  profile:{title:'My profile',edit:'Edit profile',personalInfo:'Personal information',phone:'Phone',address:'Address',missing:'Not provided',account:'Account',changePassword:'Change password',notifications:'Notifications',myBookings:'My bookings',logout:'Sign out',logoutQuestion:'Do you want to sign out?',version:'Version {{version}}',language:'Language',languageQuestion:'Select the application language',spanish:'Spanish',english:'English',portuguese:'Portuguese'},
  bookings:{title:'My bookings',upcoming:'Upcoming',history:'History',empty:'You have no bookings',confirmed:'Confirmed',pending:'Pending',completed:'Completed',cancelled:'Cancelled'},
  booking:{details:'Booking details',confirmed:'Confirmed',pending:'Pending',inProgress:'In progress',completed:'Completed',cancelled:'Cancelled',subtotal:'Subtotal',platformFee:'Platform fee',totalPaid:'Total paid',map:'Map view',cancel:'Cancel booking',contact:'Contact professional',loadError:'Failed to load booking details'},
  editProfile:{title:'Edit profile',personal:'Personal details',state:'State/Province',postalCode:'Postal code',country:'Country',updated:'Profile updated',updatedMessage:'Your changes were saved successfully',saveError:'Could not save changes',firstNameRequired:'First name is required',lastNameRequired:'Last name is required',invalidPhone:'Enter a valid phone number',invalidAddress:'Enter a valid address'},
  security:{title:'Security',change:'Change password',help:'Use at least 8 characters.',current:'Current password',new:'New password',confirm:'Confirm new password',update:'Update password',updated:'Password updated',updatedMessage:'Your password was changed successfully',updateError:'Could not change password'}
};
