export default {
  common: { error:'Error', success:'Éxito', cancel:'Cancelar', accept:'Aceptar', save:'Guardar cambios', loading:'Cargando…', quantity:'Cant.', professional:'Profesional', services:'Servicios', dateTime:'Fecha y hora', location:'Ubicación', payment:'Pago', notes:'Notas', notFound:'No encontrado', goBack:'Volver' },
  tabs: { home:'Inicio', search:'Buscar', bookings:'Reservas', profile:'Perfil' },
  categories:{limpieza:'Limpieza',electricidad:'Electricidad',plomeria:'Plomería',carpinteria:'Carpintería',pintura:'Pintura',jardineria:'Jardinería',climatizacion:'Climatización',tecnologia:'Tecnología'},
  search:{title:'Buscar',placeholder:'Buscar profesionales o servicios…',category:'Categoría',minimumRating:'Calificación mínima',sortBy:'Ordenar por',any:'Cualquiera',rating:'Calificación',price:'Precio',foundOne:'{{count}} profesional encontrado',foundMany:'{{count}} profesionales encontrados',empty:'No se encontraron profesionales',adjust:'Prueba cambiando la búsqueda o los filtros'},
  professionalDetail:{reviews:'reseñas',years:'{{count}} años',about:'Acerca de',services:'Servicios',portfolio:'Portafolio',startingAt:'Desde',bookNow:'Reservar ahora',loadError:'No se pudo cargar el profesional'},
  auth: { tagline:'Encuentra profesionales de confianza para tu hogar', email:'Correo electrónico', emailPlaceholder:'Introduce tu correo', password:'Contraseña', passwordPlaceholder:'Introduce tu contraseña', forgot:'¿Olvidaste tu contraseña?', signIn:'Iniciar sesión', or:'O', google:'Continuar con Google', apple:'Continuar con Apple', noAccount:'¿No tienes una cuenta?', signUp:'Regístrate', required:'Completa todos los campos', invalidEmail:'Introduce un correo válido', createAccount:'Crear cuenta', registerSubtitle:'Completa tus datos para registrarte', firstName:'Nombre', lastName:'Apellido', phone:'Teléfono', confirmPassword:'Confirmar contraseña', register:'Registrarse', hasAccount:'¿Ya tienes una cuenta?', passwordsMismatch:'Las contraseñas no coinciden', passwordLength:'La contraseña debe tener al menos 8 caracteres' },
  home: { title:'Buscar profesionales', subtitle:'Reserva servicios de confianza para tu hogar', top:'Profesionales destacados', seeAll:'Ver todos', empty:'No se encontraron profesionales', defaultProfessional:'Profesional', years:'{{count}} años', approved:'Aprobado', verified:'Verificado', perHour:'/hora' },
  profile: { title:'Mi perfil', edit:'Editar perfil', personalInfo:'Información personal', phone:'Teléfono', address:'Dirección', missing:'Sin registrar', account:'Cuenta', changePassword:'Cambiar contraseña', notifications:'Notificaciones', myBookings:'Mis reservas', logout:'Cerrar sesión', logoutQuestion:'¿Deseas cerrar tu sesión?', version:'Versión {{version}}', language:'Idioma', languageQuestion:'Selecciona el idioma de la aplicación', spanish:'Español', english:'Inglés', portuguese:'Portugués' },
  bookings: { title:'Mis reservas', upcoming:'Próximas', history:'Historial', empty:'No tienes reservas', confirmed:'Confirmada', pending:'Pendiente', completed:'Completada', cancelled:'Cancelada' },
  booking: { details:'Detalles de la reserva', confirmed:'Confirmada', pending:'Pendiente', inProgress:'En curso', completed:'Completada', cancelled:'Cancelada', subtotal:'Subtotal', platformFee:'Comisión de plataforma', totalPaid:'Total pagado', map:'Mapa', cancel:'Cancelar reserva', contact:'Contactar profesional', loadError:'No se pudieron cargar los detalles de la reserva', shareTitle:'Compartir comprobante PDF', shareError:'No se pudo generar o compartir el comprobante', shareFormat:'Formato del comprobante', shareFormatQuestion:'Selecciona el formato que deseas compartir', sharePdf:'Compartir PDF', sharePdfHint:'Documento listo para imprimir', shareJpeg:'Compartir JPEG', shareJpegHint:'Imagen ideal para chats y redes', jpegPreview:'Vista previa del comprobante', pdfTitle:'Comprobante de reserva', pdfReference:'Referencia de reserva', pdfIssued:'Fecha de emisión', pdfFooter:'Comprobante generado desde la aplicación. No contiene datos de pago sensibles.' },
  editProfile: { title:'Editar perfil', personal:'Datos personales', state:'Provincia/Estado', postalCode:'Código postal', country:'País', updated:'Perfil actualizado', updatedMessage:'Los cambios se guardaron correctamente', saveError:'No se pudieron guardar los cambios', firstNameRequired:'El nombre es obligatorio', lastNameRequired:'El apellido es obligatorio', invalidPhone:'Introduce un teléfono válido', invalidAddress:'Introduce una dirección válida' },
  security: { title:'Seguridad', change:'Cambiar contraseña', help:'Utiliza al menos 8 caracteres.', current:'Contraseña actual', new:'Nueva contraseña', confirm:'Confirmar nueva contraseña', update:'Actualizar contraseña', updated:'Contraseña actualizada', updatedMessage:'Tu contraseña se cambió correctamente', updateError:'No se pudo cambiar la contraseña' }
};
