export default {
  common:{error:'Erro',success:'Sucesso',cancel:'Cancelar',accept:'Aceitar',save:'Salvar alterações',loading:'Carregando…',quantity:'Qtd.',professional:'Profissional',services:'Serviços',dateTime:'Data e hora',location:'Localização',payment:'Pagamento',notes:'Observações',notFound:'Não encontrado',goBack:'Voltar'},
  tabs:{home:'Início',search:'Buscar',bookings:'Reservas',profile:'Perfil'},
  categories:{limpieza:'Limpeza',electricidad:'Eletricidade',plomeria:'Encanamento',carpinteria:'Carpintaria',pintura:'Pintura',jardineria:'Jardinagem',climatizacion:'Climatização',tecnologia:'Tecnologia'},
  search:{title:'Buscar',placeholder:'Buscar profissionais ou serviços…',category:'Categoria',minimumRating:'Avaliação mínima',sortBy:'Ordenar por',any:'Qualquer',rating:'Avaliação',price:'Preço',foundOne:'{{count}} profissional encontrado',foundMany:'{{count}} profissionais encontrados',empty:'Nenhum profissional encontrado',adjust:'Tente alterar a busca ou os filtros'},
  professionalDetail:{reviews:'avaliações',years:'{{count}} anos',about:'Sobre',services:'Serviços',portfolio:'Portfólio',startingAt:'A partir de',bookNow:'Reservar agora',loadError:'Não foi possível carregar o profissional'},
  auth:{tagline:'Encontre profissionais de confiança para sua casa',email:'E-mail',emailPlaceholder:'Digite seu e-mail',password:'Senha',passwordPlaceholder:'Digite sua senha',forgot:'Esqueceu sua senha?',signIn:'Entrar',or:'OU',google:'Continuar com Google',apple:'Continuar com Apple',noAccount:'Não tem uma conta?',signUp:'Cadastre-se',required:'Preencha todos os campos',invalidEmail:'Digite um e-mail válido',createAccount:'Criar conta',registerSubtitle:'Preencha seus dados para se cadastrar',firstName:'Nome',lastName:'Sobrenome',phone:'Telefone',confirmPassword:'Confirmar senha',register:'Cadastrar',hasAccount:'Já tem uma conta?',passwordsMismatch:'As senhas não coincidem',passwordLength:'A senha deve ter pelo menos 8 caracteres'},
  home:{title:'Buscar profissionais',subtitle:'Reserve serviços de confiança para sua casa',top:'Profissionais em destaque',seeAll:'Ver todos',empty:'Nenhum profissional encontrado',defaultProfessional:'Profissional',years:'{{count}} anos',approved:'Aprovado',verified:'Verificado',perHour:'/hora'},
  profile:{title:'Meu perfil',edit:'Editar perfil',personalInfo:'Informações pessoais',phone:'Telefone',address:'Endereço',missing:'Não informado',account:'Conta',changePassword:'Alterar senha',notifications:'Notificações',myBookings:'Minhas reservas',logout:'Sair',logoutQuestion:'Deseja sair da sua conta?',version:'Versão {{version}}',language:'Idioma',languageQuestion:'Selecione o idioma do aplicativo',spanish:'Espanhol',english:'Inglês',portuguese:'Português'},
  bookings:{title:'Minhas reservas',upcoming:'Próximas',history:'Histórico',empty:'Você não tem reservas',confirmed:'Confirmada',pending:'Pendente',completed:'Concluída',cancelled:'Cancelada'},
  booking:{details:'Detalhes da reserva',confirmed:'Confirmada',pending:'Pendente',inProgress:'Em andamento',completed:'Concluída',cancelled:'Cancelada',subtotal:'Subtotal',platformFee:'Taxa da plataforma',totalPaid:'Total pago',map:'Mapa',cancel:'Cancelar reserva',contact:'Contatar profissional',loadError:'Não foi possível carregar os detalhes da reserva',shareTitle:'Compartilhar comprovante PDF',shareError:'Não foi possível gerar ou compartilhar o comprovante',shareFormat:'Formato do comprovante',shareFormatQuestion:'Selecione o formato que deseja compartilhar',sharePdf:'Compartilhar PDF',sharePdfHint:'Documento pronto para impressão',shareJpeg:'Compartilhar JPEG',shareJpegHint:'Imagem ideal para chats e redes sociais',jpegPreview:'Prévia do comprovante',pdfTitle:'Comprovante de reserva',pdfReference:'Referência da reserva',pdfIssued:'Data de emissão',pdfFooter:'Comprovante gerado pelo aplicativo. Não contém dados de pagamento sensíveis.'},
  editProfile:{title:'Editar perfil',personal:'Dados pessoais',state:'Estado/Província',postalCode:'Código postal',country:'País',updated:'Perfil atualizado',updatedMessage:'As alterações foram salvas com sucesso',saveError:'Não foi possível salvar as alterações',firstNameRequired:'O nome é obrigatório',lastNameRequired:'O sobrenome é obrigatório',invalidPhone:'Digite um telefone válido',invalidAddress:'Digite um endereço válido'},
  security:{title:'Segurança',change:'Alterar senha',help:'Use pelo menos 8 caracteres.',current:'Senha atual',new:'Nova senha',confirm:'Confirmar nova senha',update:'Atualizar senha',updated:'Senha atualizada',updatedMessage:'Sua senha foi alterada com sucesso',updateError:'Não foi possível alterar a senha'}
};
