import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/api'
import { contentEntryListSchema, experimentListSchema, seoRedirectListSchema } from '../lib/contracts'
import { PageHeader, Pagination, QueryState, StatusBadge } from '../components/PagePrimitives'
import { dateTime } from '../lib/format'
import { useSession } from '../state/session'

type Section = 'experiments' | 'content' | 'seo'
const experimentTransitions: Record<string, string[]> = { DRAFT: ['READY', 'ARCHIVED'], READY: ['RUNNING', 'DRAFT', 'ARCHIVED'], RUNNING: ['PAUSED', 'COMPLETED'], PAUSED: ['RUNNING', 'COMPLETED', 'ARCHIVED'], COMPLETED: ['ARCHIVED',], ARCHIVED: [] }

function useListState(statuses: string[]) {
  const [page, setPage] = useState(1); const [status, setStatus] = useState('')
  const params = new URLSearchParams({ page: String(page), limit: '25' }); if (status) params.set('status', status)
  return { page, setPage, query: params.toString(), filter: <label>Estado<select aria-label="Filtrar por estado" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option value="">Todos</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label> }
}

function ExperimentsPanel() {
  const { can } = useSession(); const client = useQueryClient(); const state = useListState(['DRAFT', 'READY', 'RUNNING', 'PAUSED', 'COMPLETED', 'ARCHIVED'])
  const [change, setChange] = useState<{ id: string; next: string } | null>(null); const [reason, setReason] = useState('')
  const query = useQuery({ queryKey: ['f9-experiments', state.query], queryFn: () => api(`/v1/admin/experiments?${state.query}`, { schema: experimentListSchema }) })
  const transition = useMutation({ mutationFn: () => api(`/v1/admin/experiments/${change?.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: change?.next, reason }) }), onSuccess: async () => { setChange(null); setReason(''); await client.invalidateQueries({ queryKey: ['f9-experiments'] }) } })
  return <><div className="filters">{state.filter}</div><QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><header><div><p className="eyebrow">Server-authoritative</p><h2>Experimentos versionados</h2><p>Assignment y exposure están separados. Los resultados usan horizonte fijo, Wilson 95% y guardrails; no se declara ganador automáticamente.</p></div></header><div className="table-scroll"><table><thead><tr><th>Experimento</th><th>Estado</th><th>Mercado / superficie</th><th>Versión</th><th>Distribución</th><th>Resultado</th><th /></tr></thead><tbody>{query.data.items.map((item) => { const version = item.versions[0]; return <tr key={item.id}><td><strong>{item.name}</strong><small>{item.key} · capa {item.layerKey}</small></td><td><StatusBadge value={item.status} /><small>{item.killSwitch ? 'Kill switch activo' : 'Sirviendo tráfico'}</small></td><td>{item.market.code}<small>{item.surface}</small></td><td>{version ? `v${version.version}` : 'Sin versión'}<small>{version?.configurationDigest.slice(0, 12) || '—'}</small></td><td>{item.trafficAllocationBps / 100}%<small>{version?.variants.map((variant) => `${variant.key} ${variant.weightBps / 100}%`).join(' · ') || '—'}</small></td><td>{version?.snapshots[0] ? <><StatusBadge value={version.snapshots[0].status} /><small>{dateTime(version.snapshots[0].generatedAt)}</small></> : 'Sin snapshot'}</td><td>{can('experiments.activate') && experimentTransitions[item.status]?.map((next) => <button key={next} className="table-action" onClick={() => { setChange({ id: item.id, next }); setReason('') }}>{next}</button>)}</td></tr> })}</tbody></table></div><Pagination value={query.data.pagination} onChange={state.setPage} /></article>}</QueryState>{change && <section className="action-panel"><strong>Transición a {change.next}</strong><label>Motivo<input minLength={8} value={reason} onChange={(event) => setReason(event.target.value)} /></label><button disabled={reason.trim().length < 8 || transition.isPending} onClick={() => transition.mutate()}>Confirmar</button><button className="secondary" onClick={() => setChange(null)}>Cancelar</button>{transition.error && <p className="error" role="alert">{transition.error.message}</p>}</section>}</>
}

function ContentPanel() {
  const state = useListState(['DRAFT', 'IN_REVIEW', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'RETIRED'])
  const query = useQuery({ queryKey: ['f9-content', state.query], queryFn: () => api(`/v1/admin/content?${state.query}`, { schema: contentEntryListSchema }) })
  return <><div className="filters">{state.filter}</div><QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><header><div><p className="eyebrow">Editorial governance</p><h2>Contenido y publicaciones</h2><p>Las versiones publicadas son inmutables; aprobación y publicación exigen permisos separados y evidencia auditable.</p></div></header><div className="table-scroll"><table><thead><tr><th>Entrada</th><th>Estado</th><th>Mercado / locale</th><th>Versión</th><th>Indexación</th><th>Publicación</th></tr></thead><tbody>{query.data.items.map((item) => { const version = item.versions[0]; return <tr key={item.id}><td><strong>{version?.title || item.key}</strong><small>{item.type} · {item.key}</small></td><td><StatusBadge value={item.status} /></td><td>{item.market.code}<small>{version?.locale || '—'}</small></td><td>{version ? `v${version.version}` : '—'}<small><code>{version?.contentDigest.slice(0, 12) || '—'}</code></small></td><td><StatusBadge value={version?.indexable ? 'INDEX' : 'NOINDEX'} /><small>{version?.canonicalPath || '—'}</small></td><td>{version?.publication ? <><StatusBadge value={version.publication.status} /><small>{dateTime(version.publication.publishAt)}</small></> : 'Sin programación'}</td></tr> })}</tbody></table></div><Pagination value={query.data.pagination} onChange={state.setPage} /></article>}</QueryState></>
}

function SeoPanel() {
  const state = useListState(['ACTIVE', 'RETIRED']); const query = useQuery({ queryKey: ['f9-redirects', state.query], queryFn: () => api(`/v1/admin/seo/redirects?${state.query}`, { schema: seoRedirectListSchema }) })
  return <><div className="filters">{state.filter}</div><QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><header><div><p className="eyebrow">SEO safety</p><h2>Redirects canónicos</h2><p>Paths internos allowlisted, detección de loops y 301/308/410. El sitemap sólo incluye contenido publicado, canónico e indexable.</p></div></header><div className="table-scroll"><table><thead><tr><th>Origen</th><th>Destino</th><th>HTTP</th><th>Estado</th><th>Motivo</th><th>Creado</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td><code>{item.sourcePath}</code></td><td><code>{item.httpStatus === 410 ? 'GONE' : item.targetPath}</code></td><td>{item.httpStatus}</td><td><StatusBadge value={item.status} /></td><td>{item.reason}</td><td>{dateTime(item.createdAt)}</td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={state.setPage} /></article>}</QueryState></>
}

export function ExperimentsContentSeoPage() {
  const { can } = useSession(); const initial: Section = can('experiments.read') ? 'experiments' : can('content.read') ? 'content' : 'seo'; const [section, setSection] = useState<Section>(initial)
  const options = ([['experiments', 'Experimentos', 'experiments.read'], ['content', 'Contenido', 'content.read'], ['seo', 'SEO', 'seo.read']] as const).filter(([, , permission]) => can(permission))
  return <div className="page"><PageHeader eyebrow="F9 Experiments / Content / SEO" title="Experimentos, contenido y SEO" description="Control operacional versionado y market-aware. Mercados y producción continúan inactivos." /><nav className="section-tabs" aria-label="Módulos F9">{options.map(([value, label]) => <button key={value} className={section === value ? 'active' : ''} onClick={() => setSection(value)}>{label}</button>)}</nav>{section === 'experiments' && <ExperimentsPanel />}{section === 'content' && <ContentPanel />}{section === 'seo' && <SeoPanel />}</div>
}
