import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/api'
import { campaignListSchema, conversionListSchema, growthFunnelSchema, growthOverviewSchema, leadListSchema } from '../lib/contracts'
import { PageHeader, Pagination, QueryState, SearchBar, StatusBadge } from '../components/PagePrimitives'
import { dateTime } from '../lib/format'
import { useSession } from '../state/session'

type Section = 'overview' | 'campaigns' | 'leads' | 'conversions'
const transitions: Record<string, string[]> = { DRAFT: ['ACTIVE', 'ARCHIVED'], ACTIVE: ['PAUSED', 'ARCHIVED'], PAUSED: ['ACTIVE', 'ARCHIVED'], ARCHIVED: [] }

function GrowthOverviewPanel() {
  const overview = useQuery({ queryKey: ['growth-overview'], queryFn: () => api('/v1/admin/growth/overview', { schema: growthOverviewSchema }) })
  const funnel = useQuery({ queryKey: ['growth-funnel'], queryFn: () => api('/v1/admin/growth/funnel', { schema: growthFunnelSchema }) })
  const data = overview.data
  return <><QueryState loading={overview.isLoading} error={overview.error} empty={!data}>{data && <>
    <div className="freshness"><strong>Ventana {dateTime(data.range.from)} – {dateTime(data.range.to)}</strong><span>Timezone: {data.range.timezone}</span><span>Última recepción: {dateTime(data.freshness.latestEventReceivedAt)}</span>{data.freshness.partialData && <b>Datos históricos parciales</b>}</div>
    <section className="metric-grid">{Object.entries(data.metrics).map(([key, value]) => <article className="metric" key={key}><span>{data.definitions[key]?.label || key}</span><strong>{value}</strong><small>{data.definitions[key]?.description}</small></article>)}</section>
  </>}</QueryState>
  <QueryState loading={funnel.isLoading} error={funnel.error} empty={!funnel.data?.stages.length}>{funnel.data && <article className="panel table-panel"><header><div><p className="eyebrow">Funnel first-party</p><h2>Sujetos únicos por etapa</h2><p>{funnel.data.definition}</p></div></header><div className="table-scroll"><table><thead><tr><th>Etapa</th><th>Eventos</th><th>Sujetos</th><th>Desde inicio</th><th>Desde etapa previa</th></tr></thead><tbody>{funnel.data.stages.map((stage) => <tr key={stage.key}><td><strong>{stage.label}</strong><small>{stage.eventName}</small></td><td>{stage.occurrences}</td><td>{stage.subjects}</td><td>{stage.rateFromFirst}%</td><td>{stage.rateFromPrevious}%</td></tr>)}</tbody></table></div></article>}</QueryState></>
}

function CampaignsPanel() {
  const { can } = useSession(); const client = useQueryClient(); const [page, setPage] = useState(1); const [input, setInput] = useState(''); const [search, setSearch] = useState(''); const [showCreate, setShowCreate] = useState(false)
  const [key, setKey] = useState(''); const [name, setName] = useState(''); const [source, setSource] = useState(''); const [medium, setMedium] = useState(''); const [channel, setChannel] = useState(''); const [countryCode, setCountryCode] = useState(''); const [createReason, setCreateReason] = useState('')
  const [selected, setSelected] = useState<{ id: string; status: string } | null>(null); const [nextStatus, setNextStatus] = useState(''); const [reason, setReason] = useState('')
  const [editing, setEditing] = useState<{ id: string; name: string; source: string; medium: string; channel: string; countryCode: string } | null>(null); const [editReason, setEditReason] = useState('')
  const list = useQuery({ queryKey: ['growth-campaigns', page, search], queryFn: () => api(`/v1/admin/growth/campaigns?page=${page}&limit=25&search=${encodeURIComponent(search)}`, { schema: campaignListSchema }) })
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: ['growth-campaigns'] }), client.invalidateQueries({ queryKey: ['growth-overview'] }), client.invalidateQueries({ queryKey: ['growth-funnel'] })])
  const create = useMutation({ mutationFn: () => api('/v1/admin/growth/campaigns', { method: 'POST', body: JSON.stringify({ key, name, source, reason: createReason, ...(medium ? { medium } : {}), ...(channel ? { channel } : {}), ...(countryCode ? { countryCode } : {}) }) }), onSuccess: async () => { setShowCreate(false); setKey(''); setName(''); setSource(''); setMedium(''); setChannel(''); setCountryCode(''); setCreateReason(''); await refresh() } })
  const transition = useMutation({ mutationFn: () => api(`/v1/admin/growth/campaigns/${selected?.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: nextStatus, reason }) }), onSuccess: async () => { setSelected(null); setReason(''); await refresh() } })
  const update = useMutation({ mutationFn: () => api(`/v1/admin/growth/campaigns/${editing?.id}`, { method: 'PATCH', body: JSON.stringify({ name: editing?.name, source: editing?.source, medium: editing?.medium || null, channel: editing?.channel || null, countryCode: editing?.countryCode || null, reason: editReason }) }), onSuccess: async () => { setEditing(null); setEditReason(''); await refresh() } })
  return <><div className="section-actions">{can('marketing.manage') && <button onClick={() => setShowCreate((value) => !value)}>Nueva campaña</button>}</div>{showCreate && <section className="action-panel growth-create"><label>Clave<input value={key} onChange={(event) => setKey(event.target.value.toLowerCase())} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label><label>Nombre<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Fuente<input value={source} onChange={(event) => setSource(event.target.value)} /></label><label>Medio<input value={medium} onChange={(event) => setMedium(event.target.value)} /></label><label>Canal<input value={channel} onChange={(event) => setChannel(event.target.value)} /></label><label>País ISO<input value={countryCode} onChange={(event) => setCountryCode(event.target.value.toUpperCase())} maxLength={2} /></label><label className="wide">Motivo<input value={createReason} onChange={(event) => setCreateReason(event.target.value)} minLength={10} /></label><button disabled={key.length < 2 || name.length < 2 || !source || createReason.trim().length < 10 || create.isPending} onClick={() => create.mutate()}>Crear borrador</button>{create.error && <p className="error" role="alert">{create.error.message}</p>}</section>}
    <SearchBar value={input} onChange={setInput} onSubmit={() => { setPage(1); setSearch(input.trim()) }} placeholder="Clave, nombre o fuente" />
    <QueryState loading={list.isLoading} error={list.error} empty={!list.data?.items.length}>{list.data && <article className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Campaña</th><th>Fuente</th><th>País</th><th>Estado</th><th>Eventos</th><th>Leads</th><th>Conversiones</th><th /></tr></thead><tbody>{list.data.items.map((campaign) => <tr key={campaign.id}><td><strong>{campaign.name}</strong><small>{campaign.key}</small></td><td>{campaign.source}<small>{campaign.medium || '—'} · {campaign.channel || '—'}</small></td><td>{campaign.countryCode || 'Global'}</td><td><StatusBadge value={campaign.status} /></td><td>{campaign._count.events}</td><td>{campaign._count.leads}</td><td>{campaign._count.conversions}</td><td>{can('marketing.manage') && <><button className="table-action" disabled={campaign.status === 'ARCHIVED'} onClick={() => { setEditing({ id: campaign.id, name: campaign.name, source: campaign.source, medium: campaign.medium || '', channel: campaign.channel || '', countryCode: campaign.countryCode || '' }); setEditReason('') }}>Editar</button>{transitions[campaign.status].length > 0 && <button className="table-action" onClick={() => { setSelected(campaign); setNextStatus(transitions[campaign.status][0]); setReason('') }}>Cambiar estado</button>}</>}</td></tr>)}</tbody></table></div><Pagination value={list.data.pagination} onChange={setPage} /></article>}</QueryState>
    {editing && <section className="action-panel growth-create"><label>Nombre<input value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></label><label>Fuente<input value={editing.source} onChange={(event) => setEditing({ ...editing, source: event.target.value })} /></label><label>Medio<input value={editing.medium} onChange={(event) => setEditing({ ...editing, medium: event.target.value })} /></label><label>Canal<input value={editing.channel} onChange={(event) => setEditing({ ...editing, channel: event.target.value })} /></label><label>País ISO<input value={editing.countryCode} onChange={(event) => setEditing({ ...editing, countryCode: event.target.value.toUpperCase() })} maxLength={2} /></label><label className="wide">Motivo<input value={editReason} onChange={(event) => setEditReason(event.target.value)} minLength={10} /></label><button disabled={editing.name.trim().length < 2 || !editing.source.trim() || editReason.trim().length < 10 || update.isPending} onClick={() => update.mutate()}>Guardar cambios</button><button className="secondary" onClick={() => setEditing(null)}>Cancelar</button>{update.error && <p className="error" role="alert">{update.error.message}</p>}</section>}
    {selected && <section className="action-panel"><label>Nuevo estado<select value={nextStatus} onChange={(event) => setNextStatus(event.target.value)}>{transitions[selected.status].map((value) => <option key={value}>{value}</option>)}</select></label><label>Motivo<input value={reason} onChange={(event) => setReason(event.target.value)} minLength={10} /></label><button disabled={reason.trim().length < 10 || transition.isPending} onClick={() => transition.mutate()}>Aplicar transición</button><button className="secondary" onClick={() => setSelected(null)}>Cancelar</button>{transition.error && <p className="error" role="alert">{transition.error.message}</p>}</section>}
  </>
}

function LeadsPanel() {
  const [page, setPage] = useState(1); const [status, setStatus] = useState(''); const [countryCode, setCountryCode] = useState(''); const params = new URLSearchParams({ page: String(page), limit: '25', ...(status ? { status } : {}), ...(countryCode.length === 2 ? { countryCode } : {}) }); const list = useQuery({ queryKey: ['growth-leads', page, status, countryCode], queryFn: () => api(`/v1/admin/growth/leads?${params}`, { schema: leadListSchema }) })
  return <><div className="filters"><label><span className="sr-only">Estado del lead</span><select value={status} onChange={(event) => { setPage(1); setStatus(event.target.value) }}><option value="">Todos los estados</option>{['NEW', 'ENGAGED', 'CONVERTED', 'DISQUALIFIED'].map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="sr-only">País ISO</span><input aria-label="País ISO" value={countryCode} onChange={(event) => { setPage(1); setCountryCode(event.target.value.toUpperCase()) }} placeholder="País ISO" maxLength={2} /></label></div><QueryState loading={list.isLoading} error={list.error} empty={!list.data?.items.length}>{list.data && <article className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Última observación</th><th>Tipo</th><th>Estado</th><th>Campaña observada</th><th>Origen</th><th>Actividad</th></tr></thead><tbody>{list.data.items.map((lead) => <tr key={lead.id}><td>{dateTime(lead.lastSeenAt)}<small>Primera: {dateTime(lead.firstSeenAt)}</small></td><td>{lead.subjectType}<small>{lead.identified ? 'Identificado' : 'Seudónimo'}</small></td><td><StatusBadge value={lead.status} /></td><td>{lead.campaign?.name || 'Sin campaña'}<small>{lead.campaign?.key || '—'}</small></td><td>{lead.source || '—'}<small>{lead.channel || '—'} · {lead.countryCode || '—'}</small></td><td>{lead._count.events} eventos · {lead._count.conversions} conversiones</td></tr>)}</tbody></table></div><Pagination value={list.data.pagination} onChange={setPage} /></article>}</QueryState></>
}

function ConversionsPanel() {
  const [page, setPage] = useState(1); const [type, setType] = useState(''); const [countryCode, setCountryCode] = useState(''); const params = new URLSearchParams({ page: String(page), limit: '25', ...(type ? { type } : {}), ...(countryCode.length === 2 ? { countryCode } : {}) }); const list = useQuery({ queryKey: ['growth-conversions', page, type, countryCode], queryFn: () => api(`/v1/admin/growth/conversions?${params}`, { schema: conversionListSchema }) })
  return <><div className="filters"><label><span className="sr-only">Tipo de conversión</span><select value={type} onChange={(event) => { setPage(1); setType(event.target.value) }}><option value="">Todas las conversiones</option>{['SIGNUP', 'REQUEST', 'BOOKING', 'PAYMENT', 'JOB_COMPLETED'].map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="sr-only">País ISO</span><input aria-label="País ISO" value={countryCode} onChange={(event) => { setPage(1); setCountryCode(event.target.value.toUpperCase()) }} placeholder="País ISO" maxLength={2} /></label></div><QueryState loading={list.isLoading} error={list.error} empty={!list.data?.items.length}>{list.data && <article className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Conversión</th><th>Campaña observada</th><th>Sujeto</th><th>Correlation</th></tr></thead><tbody>{list.data.items.map((conversion) => <tr key={conversion.id}><td>{dateTime(conversion.occurredAt)}</td><td><StatusBadge value={conversion.type} /><small>{conversion.event.eventName}</small></td><td>{conversion.campaign?.name || 'Sin campaña'}<small>{conversion.campaign?.key || '—'}</small></td><td>{conversion.lead?.subjectType || 'No enlazado'}</td><td><code>{conversion.event.correlationId || '—'}</code></td></tr>)}</tbody></table></div><Pagination value={list.data.pagination} onChange={setPage} /></article>}</QueryState></>
}

export function GrowthPage() {
  const { can } = useSession(); const [section, setSection] = useState<Section>('overview')
  const tabs: Array<{ key: Section; label: string }> = [{ key: 'overview', label: 'Adquisición' }, { key: 'campaigns', label: 'Campañas' }, { key: 'leads', label: 'Leads' }, { key: 'conversions', label: 'Conversiones' }]
  return <div className="page"><PageHeader eyebrow="F6 Growth Data" title="Crecimiento" description="Eventos first-party, campañas internas, leads seudonimizados, conversiones y funnel descriptivo. Sin activación publicitaria ni attribution causal." /><nav className="operations-tabs" aria-label="Módulos de crecimiento">{tabs.map((tab) => <button key={tab.key} className={section === tab.key ? 'active' : 'secondary'} onClick={() => setSection(tab.key)}>{tab.label}</button>)}</nav>{section === 'overview' && <GrowthOverviewPanel />}{section === 'campaigns' && <CampaignsPanel />}{section === 'leads' && can('marketing.read') && <LeadsPanel />}{section === 'conversions' && can('marketing.read') && <ConversionsPanel />}</div>
}
