import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/api'
import {
  alertsSchema, errorGroupDetailSchema, errorGroupListSchema, financialMonitoringSchema,
  healthSchema, healthSnapshotsSchema, incidentDetailSchema, incidentListSchema,
  integrationsSchema, jobsSchema, operationsOverviewSchema,
} from '../lib/contracts'
import { PageHeader, Pagination, QueryState, SearchBar, StatusBadge } from '../components/PagePrimitives'
import { dateTime, moneyValue } from '../lib/format'
import { useSession } from '../state/session'

type Section = 'overview' | 'errors' | 'incidents' | 'health' | 'signals'
const errorTransitions: Record<string, string[]> = { OPEN: ['ACKNOWLEDGED', 'IGNORED'], ACKNOWLEDGED: ['RESOLVED', 'IGNORED'], RESOLVED: ['OPEN'], IGNORED: ['OPEN'] }
const incidentTransitions: Record<string, string[]> = { OPEN: ['INVESTIGATING'], INVESTIGATING: ['IDENTIFIED'], IDENTIFIED: ['MONITORING'], MONITORING: ['RESOLVED'], RESOLVED: ['CLOSED', 'INVESTIGATING'], CLOSED: ['INVESTIGATING'] }

function OverviewPanel() {
  const query = useQuery({ queryKey: ['operations-overview'], queryFn: () => api('/v1/admin/operations/overview', { schema: operationsOverviewSchema }) })
  const data = query.data
  const cards = data ? [
    ['Errores abiertos', data.errors.OPEN || 0],
    ['Incidentes activos', (data.incidents.OPEN || 0) + (data.incidents.INVESTIGATING || 0) + (data.incidents.IDENTIFIED || 0)],
    ['Dead letters', data.jobs.DEAD_LETTER || 0],
    ['Integraciones fallidas', (data.integrations.FAILED || 0) + (data.integrations.DEAD_LETTER || 0)],
    ['Refunds fallidos', data.financialAttention.failedRefunds],
    ['Payouts fallidos', data.financialAttention.failedPayouts],
    ['Disputas activas', data.financialAttention.activeDisputes],
    ['Casos de soporte activos', (data.support.OPEN || 0) + (data.support.TRIAGED || 0) + (data.support.IN_PROGRESS || 0) + (data.support.WAITING_CUSTOMER || 0)],
  ] : []
  return <QueryState loading={query.isLoading} error={query.error} empty={!data}>{data && <>
    <div className="freshness"><strong><StatusBadge value={data.health.status} /> Core API</strong><span>Generado: {dateTime(data.generatedAt)}</span><span>Último error: {dateTime(data.freshness.latestErrorAt)}</span>{data.freshness.partialData && <b>Datos parciales</b>}</div>
    <section className="metric-grid">{cards.map(([label, value]) => <article className="metric" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className="panel-grid"><article className="panel"><header><div><p className="eyebrow">Dependencias</p><h2>Readiness actual</h2></div></header><ul className="status-summary">{Object.values(data.health.dependencies).map((item) => <li key={item.service}><span>{item.service}</span><StatusBadge value={item.status} /><strong>{item.latencyMs} ms</strong></li>)}</ul></article><article className="panel"><header><div><p className="eyebrow">Reconciliación</p><h2>Última ejecución</h2></div></header>{data.financialAttention.latestReconciliation ? <div className="detail-summary"><StatusBadge value={data.financialAttention.latestReconciliation.status} /><strong>{data.financialAttention.latestReconciliation.scope}</strong><span>{data.financialAttention.latestReconciliation.mismatchCount} diferencias · {data.financialAttention.latestReconciliation.errorCount} errores</span><small>{dateTime(data.financialAttention.latestReconciliation.startedAt)}</small></div> : <p>Sin ejecuciones registradas.</p>}</article></section>
  </>}</QueryState>
}

function ErrorExplorer() {
  const [page, setPage] = useState(1); const [input, setInput] = useState(''); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<string | null>(null); const [nextStatus, setNextStatus] = useState(''); const [reason, setReason] = useState('')
  const { can } = useSession(); const queryClient = useQueryClient()
  const query = useQuery({ queryKey: ['operations-errors', page, search], queryFn: () => api(`/v1/admin/operations/errors?page=${page}&limit=25&search=${encodeURIComponent(search)}`, { schema: errorGroupListSchema }) })
  const detail = useQuery({ queryKey: ['operations-error', selected], enabled: Boolean(selected), queryFn: () => api(`/v1/admin/operations/errors/${selected}`, { schema: errorGroupDetailSchema }) })
  const mutation = useMutation({ mutationFn: () => api(`/v1/admin/operations/errors/${selected}/status`, { method: 'PATCH', body: JSON.stringify({ status: nextStatus, reason }) }), onSuccess: async () => { setReason(''); await Promise.all([queryClient.invalidateQueries({ queryKey: ['operations-errors'] }), queryClient.invalidateQueries({ queryKey: ['operations-error', selected] })]) } })
  const group = detail.data?.errorGroup
  return <><SearchBar value={input} onChange={setInput} onSubmit={() => { setPage(1); setSearch(input.trim()) }} placeholder="Código, fingerprint o mensaje" />
    <QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel operations-list"><div className="table-scroll"><table><thead><tr><th>Última vez</th><th>Severidad</th><th>Servicio</th><th>Error</th><th>Ocurrencias</th><th>Estado</th><th /></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td>{dateTime(item.lastSeenAt)}</td><td><StatusBadge value={item.severity} /></td><td>{item.service}<small>{item.module || '—'}</small></td><td><strong>{item.errorCode || 'UNCLASSIFIED'}</strong><small>{item.normalizedMessage}</small></td><td>{item.occurrenceCount}<small>{item.windowOccurrenceCount} ventana</small></td><td><StatusBadge value={item.status} /></td><td><button className="table-action" onClick={() => { setSelected(item.id); setNextStatus(errorTransitions[item.status]?.[0] || 'OPEN'); setReason('') }}>Investigar</button></td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState>
    {selected && <section className="panel operations-detail"><header><div><p className="eyebrow">Error group</p><h2>{group?.errorCode || 'Detalle seguro'}</h2></div><button className="secondary" onClick={() => setSelected(null)}>Cerrar</button></header><QueryState loading={detail.isLoading} error={detail.error} empty={!group}>{group && <><div className="detail-grid"><div><span>Fingerprint</span><code>{group.fingerprint}</code></div><div><span>Estado</span><StatusBadge value={group.status} /></div><div><span>Servicio</span><strong>{group.service}</strong></div><div><span>Ocurrencias</span><strong>{group.occurrenceCount}</strong></div></div><p>{group.normalizedMessage}</p>{can('errors.manage') && errorTransitions[group.status]?.length > 0 && <div className="action-panel"><label>Nuevo estado<select value={nextStatus} onChange={(event) => setNextStatus(event.target.value)}>{errorTransitions[group.status].map((value) => <option key={value}>{value}</option>)}</select></label><label>Motivo<input value={reason} onChange={(event) => setReason(event.target.value)} minLength={10} /></label><button disabled={reason.trim().length < 10 || mutation.isPending} onClick={() => mutation.mutate()}>Aplicar transición</button>{mutation.error && <p className="error" role="alert">{mutation.error.message}</p>}</div>}<div className="table-scroll"><table><thead><tr><th>Fecha</th><th>HTTP</th><th>Endpoint</th><th>Correlation</th><th>Trace</th></tr></thead><tbody>{group.events.map((event) => <tr key={event.id}><td>{dateTime(event.occurredAt)}</td><td>{event.httpStatus || '—'}</td><td>{event.method || '—'} {event.endpoint || '—'}</td><td><code>{event.correlationId || '—'}</code></td><td><code>{event.traceId || '—'}</code></td></tr>)}</tbody></table></div></>}</QueryState></section>}
  </>
}

function IncidentCenter() {
  const [page, setPage] = useState(1); const [input, setInput] = useState(''); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<string | null>(null); const [nextStatus, setNextStatus] = useState(''); const [reason, setReason] = useState(''); const [comment, setComment] = useState('')
  const { can } = useSession(); const queryClient = useQueryClient()
  const query = useQuery({ queryKey: ['operations-incidents', page, search], queryFn: () => api(`/v1/admin/operations/incidents?page=${page}&limit=25&search=${encodeURIComponent(search)}`, { schema: incidentListSchema }) })
  const detail = useQuery({ queryKey: ['operations-incident', selected], enabled: Boolean(selected), queryFn: () => api(`/v1/admin/operations/incidents/${selected}`, { schema: incidentDetailSchema }) })
  const refresh = () => Promise.all([queryClient.invalidateQueries({ queryKey: ['operations-incidents'] }), queryClient.invalidateQueries({ queryKey: ['operations-incident', selected] })])
  const transition = useMutation({ mutationFn: () => api(`/v1/admin/operations/incidents/${selected}/status`, { method: 'PATCH', body: JSON.stringify({ status: nextStatus, reason }) }), onSuccess: async () => { setReason(''); await refresh() } })
  const note = useMutation({ mutationFn: () => api(`/v1/admin/operations/incidents/${selected}/comments`, { method: 'POST', body: JSON.stringify({ body: comment }) }), onSuccess: async () => { setComment(''); await refresh() } })
  const incident = detail.data?.incident
  return <><SearchBar value={input} onChange={setInput} onSubmit={() => { setPage(1); setSearch(input.trim()) }} placeholder="Título o deduplication key" />
    <QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel operations-list"><div className="table-scroll"><table><thead><tr><th>Detectado</th><th>Severidad</th><th>Incidente</th><th>Servicio</th><th>Actividad</th><th>Estado</th><th /></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td>{dateTime(item.detectedAt)}</td><td><StatusBadge value={item.severity} /></td><td><strong>{item.title}</strong><small>{item.errorGroup?.errorCode || 'Sin error group'}</small></td><td>{item.service || '—'}</td><td>{item._count.events} eventos · {item._count.comments} notas</td><td><StatusBadge value={item.status} /></td><td><button className="table-action" onClick={() => { setSelected(item.id); setNextStatus(incidentTransitions[item.status]?.[0] || 'INVESTIGATING'); setReason(''); setComment('') }}>Gestionar</button></td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState>
    {selected && <section className="panel operations-detail"><header><div><p className="eyebrow">Incident Center</p><h2>{incident?.title || 'Detalle'}</h2></div><button className="secondary" onClick={() => setSelected(null)}>Cerrar</button></header><QueryState loading={detail.isLoading} error={detail.error} empty={!incident}>{incident && <><div className="detail-grid"><div><span>Estado</span><StatusBadge value={incident.status} /></div><div><span>Severidad</span><StatusBadge value={incident.severity} /></div><div><span>Servicio</span><strong>{incident.service || '—'}</strong></div><div><span>Detectado</span><strong>{dateTime(incident.detectedAt)}</strong></div></div>{incident.description && <p>{incident.description}</p>}{can('incidents.manage') && <div className="action-panel">{incidentTransitions[incident.status]?.length > 0 && <><label>Nuevo estado<select value={nextStatus} onChange={(event) => setNextStatus(event.target.value)}>{incidentTransitions[incident.status].map((value) => <option key={value}>{value}</option>)}</select></label><label>Motivo<input value={reason} onChange={(event) => setReason(event.target.value)} minLength={10} /></label><button disabled={reason.trim().length < 10 || transition.isPending} onClick={() => transition.mutate()}>Cambiar estado</button></>}<label>Nota operativa<input value={comment} onChange={(event) => setComment(event.target.value)} /></label><button disabled={!comment.trim() || note.isPending} onClick={() => note.mutate()}>Añadir nota</button>{(transition.error || note.error) && <p className="error" role="alert">{transition.error?.message || note.error?.message}</p>}</div>}<div className="timeline"><h3>Timeline</h3>{incident.events.map((event) => <article key={event.id}><StatusBadge value={event.eventType} /><span>{event.message || 'Evento operativo'}</span><time>{dateTime(event.createdAt)}</time></article>)}{incident.comments.map((entry) => <article key={entry.id}><strong>{entry.author ? `${entry.author.firstName} ${entry.author.lastName}` : 'Sistema'}</strong><span>{entry.body}</span><time>{dateTime(entry.createdAt)}</time></article>)}</div></>}</QueryState></section>}
  </>
}

function HealthPanel() {
  const current = useQuery({ queryKey: ['operations-health'], queryFn: () => api('/v1/admin/operations/health', { schema: healthSchema }), retry: false })
  const history = useQuery({ queryKey: ['operations-health-history'], queryFn: () => api('/v1/admin/operations/health/snapshots?page=1&limit=50', { schema: healthSnapshotsSchema }) })
  return <><QueryState loading={current.isLoading} error={current.error} empty={!current.data}>{current.data && <section className="panel-grid">{Object.values(current.data.dependencies).map((item) => <article className="panel" key={item.service}><header><div><p className="eyebrow">Dependencia</p><h2>{item.service}</h2></div><StatusBadge value={item.status} /></header><strong>{item.latencyMs} ms</strong><p>{item.message || 'Comprobación correcta.'}</p></article>)}</section>}</QueryState><QueryState loading={history.isLoading} error={history.error} empty={!history.data?.items.length}>{history.data && <article className="panel table-panel operations-list"><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Servicio</th><th>Estado</th><th>Latencia</th><th>Diagnóstico</th></tr></thead><tbody>{history.data.items.map((item) => <tr key={item.id}><td>{dateTime(item.checkedAt)}</td><td>{item.service}</td><td><StatusBadge value={item.status} /></td><td>{item.latencyMs ?? '—'} ms</td><td>{item.message || '—'}</td></tr>)}</tbody></table></div></article>}</QueryState></>
}

function SignalsPanel() {
  const { can } = useSession()
  const jobs = useQuery({ queryKey: ['operations-jobs'], enabled: can('jobs.read'), queryFn: () => api('/v1/admin/operations/jobs?page=1&limit=50', { schema: jobsSchema }) })
  const integrations = useQuery({ queryKey: ['operations-integrations'], enabled: can('integrations.read'), queryFn: () => api('/v1/admin/operations/integrations?page=1&limit=50', { schema: integrationsSchema }) })
  const alerts = useQuery({ queryKey: ['operations-alerts'], enabled: can('alerts.read'), queryFn: () => api('/v1/admin/operations/alerts?page=1&limit=50', { schema: alertsSchema }) })
  const financial = useQuery({ queryKey: ['operations-financial'], enabled: can('financial.monitoring.read'), queryFn: () => api('/v1/admin/operations/financial-monitoring', { schema: financialMonitoringSchema }) })
  return <div className="operations-stack">{can('jobs.read') && <QueryState loading={jobs.isLoading} error={jobs.error} empty={!jobs.data?.items.length}>{jobs.data && <SignalTable title="Jobs/outbox" items={jobs.data.items.map((item) => ({ id: item.id, createdAt: item.createdAt, type: item.eventType, source: item.aggregateType, status: item.status, attempts: item.attempts, hasError: item.hasError }))} />}</QueryState>}{can('integrations.read') && <QueryState loading={integrations.isLoading} error={integrations.error} empty={!integrations.data?.items.length}>{integrations.data && <SignalTable title="Integraciones/webhooks" items={integrations.data.items.map((item) => ({ id: item.id, createdAt: item.createdAt, type: item.eventType, source: item.provider, status: item.status, attempts: item.attempts, hasError: item.hasError }))} />}</QueryState>}{can('alerts.read') && <QueryState loading={alerts.isLoading} error={alerts.error} empty={!alerts.data?.items.length}>{alerts.data && <SignalTable title="Entregas de alertas" items={alerts.data.items.map((item) => ({ id: item.id, createdAt: item.createdAt, type: item.eventType, source: item.route || '—', status: item.status, attempts: item.attempts, hasError: item.hasError }))} />}</QueryState>}{can('financial.monitoring.read') && <QueryState loading={financial.isLoading} error={financial.error} empty={!financial.data}>{financial.data && <><div className="freshness"><strong>Monitor financiero de solo lectura</strong><span>Generado: {dateTime(financial.data.generatedAt)}</span></div><section className="panel-grid">{([['Refunds', financial.data.refunds], ['Payouts', financial.data.payouts], ['Disputas', financial.data.disputes]] as const).map(([label, rows]) => <article className="panel" key={label}><header><h2>{label}</h2></header><ul className="status-summary">{rows.map((row) => <li key={`${row.status}-${row.currency}`}><StatusBadge value={row.status} /><strong>{row.count}</strong><span>{moneyValue(row.amount, row.currency)}</span></li>)}</ul></article>)}</section></>}</QueryState>}</div>
}

function SignalTable({ title, items }: { title: string; items: Array<{ id: string; createdAt: string; type: string; source: string; status: string; attempts: number; hasError: boolean }> }) {
  return <article className="panel table-panel"><header className="signal-title"><div><p className="eyebrow">Señal operativa</p><h2>{title}</h2></div></header><div className="table-scroll"><table><thead><tr><th>Creado</th><th>Tipo</th><th>Origen/ruta</th><th>Estado</th><th>Intentos</th><th>Fallo</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{dateTime(item.createdAt)}</td><td>{item.type}</td><td>{item.source}</td><td><StatusBadge value={item.status} /></td><td>{item.attempts}</td><td>{item.hasError ? 'Sí — revisar runbook' : 'No'}</td></tr>)}</tbody></table></div></article>
}

export function OperationsPage() {
  const { can } = useSession(); const [section, setSection] = useState<Section>('overview')
  const tabs = [{ key: 'overview' as const, label: 'Overview', show: true }, { key: 'errors' as const, label: 'Errores', show: can('errors.read') }, { key: 'incidents' as const, label: 'Incidentes', show: can('incidents.read') }, { key: 'health' as const, label: 'Health', show: can('health.read') }, { key: 'signals' as const, label: 'Jobs, integraciones y finanzas', show: can('jobs.read') || can('integrations.read') || can('alerts.read') || can('financial.monitoring.read') }]
  return <div className="page"><PageHeader eyebrow="Operations Control" title="Centro operativo" description="Errores, incidentes, dependencias, trabajo asíncrono, integraciones, alertas y señales financieras con contexto seguro." /><nav className="operations-tabs" aria-label="Módulos operativos">{tabs.filter((tab) => tab.show).map((tab) => <button className={section === tab.key ? 'active' : 'secondary'} key={tab.key} onClick={() => setSection(tab.key)}>{tab.label}</button>)}</nav>{section === 'overview' && <OverviewPanel />}{section === 'errors' && <ErrorExplorer />}{section === 'incidents' && <IncidentCenter />}{section === 'health' && <HealthPanel />}{section === 'signals' && <SignalsPanel />}</div>
}
