import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/api'
import {
  attributionListSchema, attributionModelListSchema, consentDecisionListSchema,
  consentPolicyListSchema, touchpointListSchema,
} from '../lib/contracts'
import { PageHeader, Pagination, QueryState, StatusBadge } from '../components/PagePrimitives'
import { dateTime } from '../lib/format'
import { useSession } from '../state/session'

type Section = 'policies' | 'history' | 'withdrawals' | 'touchpoints' | 'models' | 'attributions'
const listPath = (path: string, page: number, purpose: string) => `${path}?${new URLSearchParams({ page: String(page), limit: '25', ...(purpose ? { purpose } : {}) })}`

function PurposeFilter({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <div className="filters"><label>Purpose<input value={value} onChange={(event) => onChange(event.target.value.toLowerCase())} placeholder="marketing_attribution" /></label></div>
}

function PoliciesPanel() {
  const { can } = useSession(); const queryClient = useQueryClient(); const [page, setPage] = useState(1); const [purpose, setPurpose] = useState('')
  const [showCreate, setShowCreate] = useState(false); const [key, setKey] = useState(''); const [policyPurpose, setPolicyPurpose] = useState('marketing_attribution'); const [version, setVersion] = useState(1); const [countryCode, setCountryCode] = useState('ES'); const [locale, setLocale] = useState('es'); const [legalBasis, setLegalBasis] = useState('consent'); const [enforcementMode, setEnforcementMode] = useState('EXPLICIT_GRANT'); const [documentReference, setDocumentReference] = useState(''); const [documentDigest, setDocumentDigest] = useState(''); const [retentionDays, setRetentionDays] = useState(''); const [reason, setReason] = useState('')
  const [reviewing, setReviewing] = useState<string | null>(null); const [reviewReference, setReviewReference] = useState(''); const [reviewReason, setReviewReason] = useState('')
  const query = useQuery({ queryKey: ['privacy-policies', page, purpose], queryFn: () => api(listPath('/v1/admin/privacy/policies', page, purpose), { schema: consentPolicyListSchema }) })
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['privacy-policies'] })
  const create = useMutation({ mutationFn: () => api('/v1/admin/privacy/policies', { method: 'POST', body: JSON.stringify({ key, purpose: policyPurpose, version, countryCode, locale, legalBasis, enforcementMode, documentReference, documentDigest, ...(retentionDays ? { retentionDays: Number(retentionDays) } : {}), reason }) }), onSuccess: async () => { setShowCreate(false); await refresh() } })
  const review = useMutation({ mutationFn: () => api(`/v1/admin/privacy/policies/${reviewing}/review`, { method: 'POST', body: JSON.stringify({ reviewStatus: 'APPROVED', reviewReference, reason: reviewReason }) }), onSuccess: async () => { setReviewing(null); await refresh() } })
  const status = useMutation({ mutationFn: ({ id, next }: { id: string; next: string }) => api(`/v1/admin/privacy/policies/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status: next, reason: `${next === 'ACTIVE' ? 'Activate' : 'Retire'} reviewed policy version.` }) }), onSuccess: refresh })
  return <><PurposeFilter value={purpose} onChange={(value) => { setPurpose(value); setPage(1) }} />{can('privacy.policy.manage') && <button onClick={() => setShowCreate((value) => !value)}>Nueva versión de política</button>}
    {showCreate && <section className="action-panel growth-create"><label>Clave<input value={key} onChange={(e) => setKey(e.target.value.toLowerCase())} /></label><label>Purpose<input value={policyPurpose} onChange={(e) => setPolicyPurpose(e.target.value.toLowerCase())} /></label><label>Versión<input type="number" min="1" value={version} onChange={(e) => setVersion(Number(e.target.value))} /></label><label>País<input value={countryCode} maxLength={2} onChange={(e) => setCountryCode(e.target.value.toUpperCase())} /></label><label>Locale<input value={locale} onChange={(e) => setLocale(e.target.value)} /></label><label>Base jurídica<input value={legalBasis} onChange={(e) => setLegalBasis(e.target.value.toLowerCase())} /></label><label>Enforcement<select value={enforcementMode} onChange={(e) => setEnforcementMode(e.target.value)}><option>EXPLICIT_GRANT</option><option>POLICY_ONLY</option><option>PROHIBITED</option></select></label><label className="wide">Documento<input value={documentReference} onChange={(e) => setDocumentReference(e.target.value)} /></label><label className="wide">SHA-256 del documento<input value={documentDigest} onChange={(e) => setDocumentDigest(e.target.value.toLowerCase())} maxLength={64} /></label><label>Retención aprobada (días)<input type="number" min="1" max="3650" value={retentionDays} onChange={(e) => setRetentionDays(e.target.value)} /></label><label className="wide">Motivo<input value={reason} onChange={(e) => setReason(e.target.value)} /></label><button disabled={!key || documentDigest.length !== 64 || reason.trim().length < 10 || create.isPending} onClick={() => create.mutate()}>Crear draft</button>{create.error && <p className="error" role="alert">{create.error.message}</p>}</section>}
    <QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Política</th><th>Ámbito</th><th>Base / modo</th><th>Revisión</th><th>Estado</th><th>Vigencia</th><th /></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td><strong>{item.key} v{item.version}</strong><small><a href={item.documentReference} target="_blank" rel="noreferrer">Documento</a> · {item.documentDigest.slice(0, 12)}…</small></td><td>{item.purpose}<small>{item.countryCode} · {item.locale}</small></td><td>{item.legalBasis}<small>{item.enforcementMode}</small></td><td><StatusBadge value={item.reviewStatus} /><small>{item.reviewReference || 'Sin evidencia'}</small></td><td><StatusBadge value={item.status} /></td><td>{dateTime(item.effectiveAt)}<small>Retiro: {dateTime(item.retiredAt)}</small></td><td>{can('privacy.policy.manage') && <>{item.status === 'DRAFT' && item.reviewStatus !== 'APPROVED' && <button className="table-action" onClick={() => setReviewing(item.id)}>Revisar</button>}{item.status === 'DRAFT' && item.reviewStatus === 'APPROVED' && <button className="table-action" onClick={() => status.mutate({ id: item.id, next: 'ACTIVE' })}>Activar</button>}{item.status === 'ACTIVE' && <button className="table-action" onClick={() => status.mutate({ id: item.id, next: 'RETIRED' })}>Retirar</button>}</>}</td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState>
    {reviewing && <section className="action-panel"><label>Referencia de revisión<input value={reviewReference} onChange={(e) => setReviewReference(e.target.value)} /></label><label>Motivo<input value={reviewReason} onChange={(e) => setReviewReason(e.target.value)} /></label><button disabled={reviewReference.length < 8 || reviewReason.length < 10 || review.isPending} onClick={() => review.mutate()}>Aprobar revisión</button><button className="secondary" onClick={() => setReviewing(null)}>Cancelar</button>{review.error && <p className="error" role="alert">{review.error.message}</p>}</section>}
  </>
}

function DecisionsPanel({ withdrawals = false }: { withdrawals?: boolean }) {
  const [page, setPage] = useState(1); const [purpose, setPurpose] = useState(''); const path = withdrawals ? '/v1/admin/privacy/withdrawals' : '/v1/admin/privacy/consents'
  const query = useQuery({ queryKey: [withdrawals ? 'privacy-withdrawals' : 'privacy-history', page, purpose], queryFn: () => api(listPath(path, page, purpose), { schema: consentDecisionListSchema }) })
  return <><PurposeFilter value={purpose} onChange={(value) => { setPurpose(value); setPage(1) }} /><QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Purpose</th><th>Decisión</th><th>Versión</th><th>Sujeto</th><th>Origen</th><th>Correlation</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td>{dateTime(item.occurredAt)}</td><td>{item.purpose}<small>{item.policy.countryCode} · {item.policy.locale}</small></td><td><StatusBadge value={item.decision} /></td><td>{item.policy.key} v{item.policyVersion}</td><td>{item.subjectType}<small>{item.userId || 'seudónimo'}</small></td><td>{item.source}</td><td><code>{item.correlationId || '—'}</code></td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState></>
}

function TouchpointsPanel() {
  const [page, setPage] = useState(1); const [purpose, setPurpose] = useState(''); const query = useQuery({ queryKey: ['privacy-touchpoints', page, purpose], queryFn: () => api(listPath('/v1/admin/privacy/touchpoints', page, purpose), { schema: touchpointListSchema }) })
  return <><PurposeFilter value={purpose} onChange={(value) => { setPurpose(value); setPage(1) }} /><QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Fuente</th><th>Referrer normalizado</th><th>Landing</th><th>Sujeto</th><th>Correlation</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td>{dateTime(item.occurredAt)}</td><td>{item.source}<small>{item.medium || '—'} · {item.channel || '—'}</small></td><td>{item.referrerOrigin || '—'}<small>{item.referrerPath || '—'}</small></td><td>{item.landingPath || '—'}</td><td>{item.subjectType}</td><td><code>{item.correlationId || '—'}</code></td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState></>
}

function ModelsPanel() {
  const { can } = useSession(); const queryClient = useQueryClient(); const [page, setPage] = useState(1); const [purpose, setPurpose] = useState(''); const [showCreate, setShowCreate] = useState(false); const [key, setKey] = useState(''); const [name, setName] = useState(''); const [version, setVersion] = useState(1); const [type, setType] = useState('FIRST_TOUCH'); const [modelPurpose, setModelPurpose] = useState('marketing_attribution'); const [windowDays, setWindowDays] = useState(30); const [reason, setReason] = useState('')
  const query = useQuery({ queryKey: ['attribution-models', page, purpose], queryFn: () => api(listPath('/v1/admin/attribution/models', page, purpose), { schema: attributionModelListSchema }) }); const refresh = () => queryClient.invalidateQueries({ queryKey: ['attribution-models'] })
  const create = useMutation({ mutationFn: () => api('/v1/admin/attribution/models', { method: 'POST', body: JSON.stringify({ key, name, version, type, purpose: modelPurpose, windowDays, reason }) }), onSuccess: async () => { setShowCreate(false); await refresh() } })
  const status = useMutation({ mutationFn: ({ id, next }: { id: string; next: string }) => api(`/v1/admin/attribution/models/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status: next, reason: `${next === 'ACTIVE' ? 'Activate' : 'Retire'} attribution model version.` }) }), onSuccess: refresh })
  return <><PurposeFilter value={purpose} onChange={(value) => { setPurpose(value); setPage(1) }} />{can('attribution.manage') && <button onClick={() => setShowCreate((value) => !value)}>Nuevo modelo</button>}{showCreate && <section className="action-panel growth-create"><label>Clave<input value={key} onChange={(e) => setKey(e.target.value.toLowerCase())} /></label><label>Nombre<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Versión<input type="number" min="1" value={version} onChange={(e) => setVersion(Number(e.target.value))} /></label><label>Tipo<select value={type} onChange={(e) => setType(e.target.value)}><option>FIRST_TOUCH</option><option>LAST_TOUCH</option></select></label><label>Purpose<input value={modelPurpose} onChange={(e) => setModelPurpose(e.target.value.toLowerCase())} /></label><label>Ventana (días)<input type="number" min="1" max="366" value={windowDays} onChange={(e) => setWindowDays(Number(e.target.value))} /></label><label className="wide">Motivo<input value={reason} onChange={(e) => setReason(e.target.value)} /></label><button disabled={!key || name.length < 2 || reason.length < 10 || create.isPending} onClick={() => create.mutate()}>Crear draft</button>{create.error && <p className="error" role="alert">{create.error.message}</p>}</section>}<QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Modelo</th><th>Purpose</th><th>Tipo</th><th>Ventana</th><th>Estado</th><th>Vigencia</th><th /></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.key} v{item.version}</small></td><td>{item.purpose}</td><td>{item.type}</td><td>{item.windowDays} días</td><td><StatusBadge value={item.status} /></td><td>{dateTime(item.effectiveAt)}<small>Retiro: {dateTime(item.retiredAt)}</small></td><td>{can('attribution.manage') && <>{item.status === 'DRAFT' && <button className="table-action" onClick={() => status.mutate({ id: item.id, next: 'ACTIVE' })}>Activar</button>}{item.status === 'ACTIVE' && <button className="table-action" onClick={() => status.mutate({ id: item.id, next: 'RETIRED' })}>Retirar</button>}</>}</td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState></>
}

function AttributionsPanel() {
  const [page, setPage] = useState(1); const [purpose, setPurpose] = useState(''); const query = useQuery({ queryKey: ['attributions', page, purpose], queryFn: () => api(listPath('/v1/admin/attribution/results', page, purpose), { schema: attributionListSchema }) })
  return <><PurposeFilter value={purpose} onChange={(value) => { setPurpose(value); setPage(1) }} /><QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Cálculo</th><th>Conversión</th><th>Modelo</th><th>Resultado</th><th>Touchpoint</th><th>Ventana</th><th>Correlation</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td>{dateTime(item.calculatedAt)}<small><code>{item.inputDigest.slice(0, 12)}…</code></small></td><td>{item.conversion.type}<small>{dateTime(item.conversion.occurredAt)}</small></td><td>{item.model.name}<small>{item.model.type} · v{item.model.version}</small></td><td><StatusBadge value={item.status} /><small>{item.reasonCode}</small></td><td>{item.touchpoint?.source || 'Sin atribuir'}<small>{item.touchpoint ? dateTime(item.touchpoint.occurredAt) : '—'}</small></td><td>{dateTime(item.windowStartedAt)}<small>hasta {dateTime(item.windowEndedAt)}</small></td><td><code>{item.correlationId || '—'}</code></td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState></>
}

export function PrivacyAttributionPage() {
  const { can } = useSession(); const tabs: Array<{ key: Section; label: string; permission: string }> = [
    { key: 'policies', label: 'Consent Policies', permission: 'privacy.policy.read' }, { key: 'history', label: 'Consent History', permission: 'privacy.consent.read' },
    { key: 'withdrawals', label: 'Withdrawals', permission: 'privacy.consent.read' }, { key: 'touchpoints', label: 'Touchpoints', permission: 'touchpoints.read' },
    { key: 'models', label: 'Modelos y ventanas', permission: 'attribution.read' }, { key: 'attributions', label: 'Attribution', permission: 'attribution.read' },
  ]; const allowed = tabs.filter((item) => can(item.permission)); const [section, setSection] = useState<Section>(allowed[0]?.key || 'policies')
  return <div className="page"><PageHeader eyebrow="F7 Consent & Attribution" title="Privacidad y atribución" description="Políticas versionadas, decisiones inmutables, retiros, touchpoints first-party y resultados reproducibles. Producción permanece desactivada." /><nav className="operations-tabs" aria-label="Privacidad y atribución">{allowed.map((tab) => <button key={tab.key} className={section === tab.key ? 'active' : 'secondary'} onClick={() => setSection(tab.key)}>{tab.label}</button>)}</nav>{section === 'policies' && <PoliciesPanel />}{section === 'history' && <DecisionsPanel />}{section === 'withdrawals' && <DecisionsPanel withdrawals />}{section === 'touchpoints' && <TouchpointsPanel />}{section === 'models' && <ModelsPanel />}{section === 'attributions' && <AttributionsPanel />}</div>
}
