import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/api'
import { aiCostListSchema, aiExecutionListSchema, aiOperationListSchema, aiProviderListSchema, expansionListSchema, readinessEvaluationListSchema, supplyDemandSnapshotListSchema } from '../lib/contracts'
import { PageHeader, Pagination, QueryState, StatusBadge } from '../components/PagePrimitives'
import { dateTime } from '../lib/format'
import { useSession } from '../state/session'

type Section = 'balance' | 'readiness' | 'expansion' | 'ai'
const pagination = (page: number) => new URLSearchParams({ page: String(page), limit: '25' }).toString()
const numberFrom = (value: unknown) => typeof value === 'number' ? value : 0

function BalancePanel() {
  const [page, setPage] = useState(1); const query = useQuery({ queryKey: ['f10-snapshots', page], queryFn: () => api(`/v1/admin/supply-demand/snapshots?${pagination(page)}`, { schema: supplyDemandSnapshotListSchema }) })
  return <QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><header><div><p className="eyebrow">Deterministic metrics</p><h2>Oferta y demanda</h2><p>Snapshots inmutables con ventana, watermark, calidad, componentes y reglas de anomalía explícitas. El tráfico SEO no se contabiliza como demanda económica.</p></div></header><div className="table-scroll"><table><thead><tr><th>Mercado / alcance</th><th>Ventana</th><th>Supply</th><th>Demand</th><th>Balance</th><th>Calidad</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td><strong>{item.market.code}</strong><small>{item.division?.canonicalName || 'Todo el mercado'} · {item.service?.name || 'Todos los servicios'}</small></td><td>{item.window}<small>{dateTime(item.windowStart)} → {dateTime(item.windowEnd)}</small></td><td>{numberFrom(item.components.eligibleProfessionals)} elegibles<small>{numberFrom(item.components.verifiedProfessionals)} verificados · {numberFrom(item.components.activeServiceAreas)} áreas</small></td><td>{numberFrom(item.components.requestDemand)} requests<small>{numberFrom(item.components.unmetDemand)} sin cubrir · {numberFrom(item.components.bookingAttempts)} intentos</small></td><td>{(numberFrom(item.balance.fulfilmentRate) * 100).toFixed(1)}% fulfilment<small>{numberFrom(item.balance.requestsPerProfessional).toFixed(2)} requests/pro · {(numberFrom(item.balance.geographicCoverage) * 100).toFixed(1)}% coverage</small></td><td><StatusBadge value={item.status} /><small>{item.anomalies.length} anomalías · {item.missingEvidence.length} gaps</small></td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState>
}

function ReadinessPanel() {
  const [page, setPage] = useState(1); const query = useQuery({ queryKey: ['f10-readiness', page], queryFn: () => api(`/v1/admin/readiness/evaluations?${pagination(page)}`, { schema: readinessEvaluationListSchema }) })
  return <QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><header><div><p className="eyebrow">Evidence, not activation</p><h2>Market readiness</h2><p>READY es una evaluación versionada. Nunca cambia el estado de Market ni sustituye la aprobación humana de F8.5.</p></div></header><div className="table-scroll"><table><thead><tr><th>Mercado</th><th>Resultado</th><th>Política</th><th>Blockers</th><th>Evidencia faltante</th><th>Evaluado</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td><strong>{item.market.code}</strong><small>Market: {item.market.status}</small></td><td><StatusBadge value={item.outcome} /></td><td>{item.policy.key} v{item.policy.version}<small>{item.algorithmVersion}</small></td><td>{item.blockers.length ? item.blockers.join(', ') : 'Ninguno'}</td><td>{item.missingEvidence.length ? item.missingEvidence.join(', ') : 'Completa'}</td><td>{dateTime(item.evaluatedAt)}</td></tr>)}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState>
}

function ExpansionPanel() {
  const [page, setPage] = useState(1); const query = useQuery({ queryKey: ['f10-expansion', page], queryFn: () => api(`/v1/admin/expansion?${pagination(page)}`, { schema: expansionListSchema }) })
  return <QueryState loading={query.isLoading} error={query.error} empty={!query.data?.items.length}>{query.data && <article className="panel table-panel"><header><div><p className="eyebrow">Recommendation only</p><h2>Candidatos de expansión</h2><p>La revisión acepta evidencia y recomendación; no activa mercados, servicios, geografía, pricing ni movimientos financieros.</p></div></header><div className="table-scroll"><table><thead><tr><th>Candidato</th><th>Mercado</th><th>Hipótesis</th><th>Recomendación</th><th>Confianza</th><th>Estado</th></tr></thead><tbody>{query.data.items.map((item) => { const evaluation = item.evaluations[0]; return <tr key={item.id}><td><strong>{item.type}</strong><small>{item.division?.canonicalName || item.service?.name || 'Market scope'}</small></td><td>{item.market.code}<small>{item.market.status}</small></td><td>{item.hypothesis}</td><td>{evaluation?.recommendation || 'Sin evaluar'}<small>{evaluation?.blockers.join(', ') || '—'}</small></td><td>{evaluation ? `${evaluation.confidenceBps / 100}%` : '—'}</td><td><StatusBadge value={evaluation?.reviewStatus || item.status} /></td></tr> })}</tbody></table></div><Pagination value={query.data.pagination} onChange={setPage} /></article>}</QueryState>
}

function AIPanel() {
  const { can } = useSession(); const client = useQueryClient(); const [tab, setTab] = useState<'operations' | 'executions' | 'providers' | 'costs'>('operations'); const [review, setReview] = useState<{ id: string; digest: string; decision: 'APPROVED' | 'REJECTED' } | null>(null); const [reason, setReason] = useState('')
  const operations = useQuery({ queryKey: ['f10-ai-operations'], queryFn: () => api('/v1/admin/ai/operations?page=1&limit=25', { schema: aiOperationListSchema }), enabled: tab === 'operations' })
  const executions = useQuery({ queryKey: ['f10-ai-executions'], queryFn: () => api('/v1/admin/ai/executions?page=1&limit=25', { schema: aiExecutionListSchema }), enabled: tab === 'executions' })
  const providers = useQuery({ queryKey: ['f10-ai-providers'], queryFn: () => api('/v1/admin/ai/providers?page=1&limit=25', { schema: aiProviderListSchema }), enabled: tab === 'providers' })
  const costs = useQuery({ queryKey: ['f10-ai-costs'], queryFn: () => api('/v1/admin/ai/costs?page=1&limit=25', { schema: aiCostListSchema }), enabled: tab === 'costs' })
  const approval = useMutation({ mutationFn: () => api(`/v1/admin/ai/executions/${review?.id}/approvals`, { method: 'POST', body: JSON.stringify({ decision: review?.decision, artifactDigest: review?.digest, reason }) }), onSuccess: async () => { setReview(null); setReason(''); await client.invalidateQueries({ queryKey: ['f10-ai-executions'] }) } })
  return <><nav className="section-tabs" aria-label="AI Operations views">{(['operations', 'executions', 'providers', 'costs'] as const).filter((value) => value !== 'providers' || can('ai.providers.read')).filter((value) => value !== 'costs' || can('ai.costs.read')).map((value) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{value}</button>)}</nav>
    {tab === 'operations' && <QueryState loading={operations.isLoading} error={operations.error} empty={!operations.data?.items.length}>{operations.data && <article className="panel table-panel"><header><h2>Registry de operaciones</h2><p>Sin prompt arbitrario. Prompt, schema, tools, riesgo y evaluación están versionados.</p></header><div className="table-scroll"><table><thead><tr><th>Operación</th><th>Estado</th><th>Riesgo</th><th>Prompt</th><th>Evaluation</th></tr></thead><tbody>{operations.data.items.map((item) => { const version = item.versions[0]; return <tr key={item.id}><td><strong>{item.key}</strong><small>{item.kind}</small></td><td><StatusBadge value={item.status} /></td><td>{version?.riskClass || '—'}<small>{version?.approvalRequired ? 'Approval requerido' : 'Sin efecto sensible'}</small></td><td>{version ? `v${version.promptVersion.version} ${version.promptVersion.status}` : '—'}</td><td><StatusBadge value={version?.evaluations[0]?.status || 'PENDING'} /></td></tr> })}</tbody></table></div></article>}</QueryState>}
    {tab === 'executions' && <QueryState loading={executions.isLoading} error={executions.error} empty={!executions.data?.items.length}>{executions.data && <article className="panel table-panel"><header><h2>Ejecuciones y approvals</h2><p>Inputs redactados, routing auditable, outputs estructurados y four-eyes para HIGH.</p></header><div className="table-scroll"><table><thead><tr><th>Operación</th><th>Estado</th><th>Ruta</th><th>Intentos</th><th>Evidencia</th><th /></tr></thead><tbody>{executions.data.items.map((item) => <tr key={item.id}><td><strong>{item.operationVersion.definition.key}</strong><small>{item.operationVersion.riskClass} · {item.dataClass}</small></td><td><StatusBadge value={item.status} /><small>{item.lastErrorCode || '—'}</small></td><td>{item.provider?.key || 'Sin provider'}<small>{item.modelPolicy ? `${item.modelPolicy.key} v${item.modelPolicy.version}` : 'Sin model route'}</small></td><td>{item.attemptCount}<small>{dateTime(item.createdAt)}</small></td><td><code>{item.outputArtifact?.contentDigest.slice(0, 12) || item.correlationId || '—'}</code></td><td>{can('ai.approve') && item.status === 'AWAITING_APPROVAL' && item.outputArtifact && <><button className="table-action" onClick={() => setReview({ id: item.id, digest: item.outputArtifact!.contentDigest, decision: 'APPROVED' })}>Aprobar</button><button className="table-action" onClick={() => setReview({ id: item.id, digest: item.outputArtifact!.contentDigest, decision: 'REJECTED' })}>Rechazar</button></>}</td></tr>)}</tbody></table></div></article>}</QueryState>}
    {tab === 'providers' && <QueryState loading={providers.isLoading} error={providers.error} empty={!providers.data?.items.length}>{providers.data && <article className="panel table-panel"><header><h2>Provider y model policy</h2><p>Credenciales sólo por referencia al secret store; endpoints y adapters están allowlisted.</p></header><div className="table-scroll"><table><thead><tr><th>Provider</th><th>Estado</th><th>Adapter</th><th>Clasificación</th><th>Límites</th></tr></thead><tbody>{providers.data.items.map((item) => <tr key={item.id}><td><strong>{item.displayName}</strong><small>{item.key} · {item.region || 'region policy'}</small></td><td><StatusBadge value={item.status} /></td><td>{item.adapterType}</td><td>{item.maximumDataClass}</td><td>{item.maxConcurrency} concurrentes<small>{item.requestsPerMinute}/min · {item.timeoutMs}ms</small></td></tr>)}</tbody></table></div></article>}</QueryState>}
    {tab === 'costs' && <QueryState loading={costs.isLoading} error={costs.error} empty={!costs.data?.items.length}>{costs.data && <article className="panel table-panel"><header><h2>Cost evidence</h2><p>Estimado: {costs.data.totals.estimatedCostMicros} μ{costs.data.items[0]?.currency || 'USD'} · input {costs.data.totals.inputTokens || 0} tokens · output {costs.data.totals.outputTokens || 0} tokens.</p></header><div className="table-scroll"><table><thead><tr><th>Provider</th><th>Model policy</th><th>Tokens</th><th>Coste estimado</th><th>Registrado</th></tr></thead><tbody>{costs.data.items.map((item) => <tr key={item.id}><td>{item.provider.key}</td><td>{item.modelPolicy.key} v{item.modelPolicy.version}</td><td>{item.inputTokens + item.outputTokens}</td><td>{item.estimatedCostMicros} μ{item.currency}</td><td>{dateTime(item.recordedAt)}</td></tr>)}</tbody></table></div></article>}</QueryState>}
    {review && <section className="action-panel"><strong>{review.decision === 'APPROVED' ? 'Aprobar' : 'Rechazar'} output exacto</strong><label>Motivo<input minLength={8} value={reason} onChange={(event) => setReason(event.target.value)} /></label><button disabled={reason.trim().length < 8 || approval.isPending} onClick={() => approval.mutate()}>Confirmar decisión</button><button className="secondary" onClick={() => setReview(null)}>Cancelar</button>{approval.error && <p className="error" role="alert">{approval.error.message}</p>}</section>}</>
}

export function SupplyDemandAIPage() {
  const { can } = useSession(); const options = ([['balance', 'Supply / Demand', 'supplyDemand.read'], ['readiness', 'Readiness', 'readiness.read'], ['expansion', 'Expansion', 'expansion.read'], ['ai', 'AI Operations', 'ai.operations.read']] as const).filter(([, , permission]) => can(permission)); const [section, setSection] = useState<Section>((options[0]?.[0] || 'balance') as Section)
  return <div className="page"><PageHeader eyebrow="F10 Supply / Demand + AI Operations" title="Inteligencia operacional gobernada" description="Métricas deterministas, readiness explicable y AI no autoritativa. Producción y Markets siguen inactivos." /><nav className="section-tabs" aria-label="Módulos F10">{options.map(([value, label]) => <button key={value} className={section === value ? 'active' : ''} onClick={() => setSection(value)}>{label}</button>)}</nav>{section === 'balance' && <BalancePanel />}{section === 'readiness' && <ReadinessPanel />}{section === 'expansion' && <ExpansionPanel />}{section === 'ai' && <AIPanel />}</div>
}
