import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../lib/api'
import { supportCaseDetailSchema, supportCaseListSchema, supportOperatorsSchema } from '../lib/contracts'
import { PageHeader, Pagination, QueryState, SearchBar, StatusBadge } from '../components/PagePrimitives'
import { dateTime } from '../lib/format'
import { useSession } from '../state/session'

const transitions: Record<string, string[]> = { OPEN: ['TRIAGED'], TRIAGED: ['IN_PROGRESS', 'CLOSED'], IN_PROGRESS: ['WAITING_CUSTOMER', 'RESOLVED'], WAITING_CUSTOMER: ['IN_PROGRESS', 'RESOLVED'], RESOLVED: ['CLOSED', 'IN_PROGRESS'], CLOSED: ['IN_PROGRESS'] }

export function SupportPage() {
  const { can } = useSession(); const client = useQueryClient()
  const [page, setPage] = useState(1); const [input, setInput] = useState(''); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<string | null>(null); const [showCreate, setShowCreate] = useState(false)
  const [subject, setSubject] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState('OTHER'); const [priority, setPriority] = useState('MEDIUM')
  const [nextStatus, setNextStatus] = useState(''); const [reason, setReason] = useState(''); const [comment, setComment] = useState(''); const [assignee, setAssignee] = useState('')
  const list = useQuery({ queryKey: ['support-cases', page, search], queryFn: () => api(`/v1/admin/operations/support/cases?page=${page}&limit=25&search=${encodeURIComponent(search)}`, { schema: supportCaseListSchema }) })
  const detail = useQuery({ queryKey: ['support-case', selected], enabled: Boolean(selected), queryFn: () => api(`/v1/admin/operations/support/cases/${selected}`, { schema: supportCaseDetailSchema }) })
  const operators = useQuery({ queryKey: ['support-operators'], enabled: can('support.manage'), queryFn: () => api('/v1/admin/operations/support/operators', { schema: supportOperatorsSchema }) })
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: ['support-cases'] }), client.invalidateQueries({ queryKey: ['support-case', selected] })])
  const create = useMutation({ mutationFn: () => api('/v1/admin/operations/support/cases', { method: 'POST', body: JSON.stringify({ subject, description, category, priority }) }), onSuccess: async () => { setShowCreate(false); setSubject(''); setDescription(''); await refresh() } })
  const changeStatus = useMutation({ mutationFn: () => api(`/v1/admin/operations/support/cases/${selected}/status`, { method: 'PATCH', body: JSON.stringify({ status: nextStatus, reason }) }), onSuccess: async () => { setReason(''); await refresh() } })
  const assign = useMutation({ mutationFn: () => api(`/v1/admin/operations/support/cases/${selected}/assignment`, { method: 'PATCH', body: JSON.stringify({ assignedToId: assignee || null, reason }) }), onSuccess: async () => { setReason(''); await refresh() } })
  const addComment = useMutation({ mutationFn: () => api(`/v1/admin/operations/support/cases/${selected}/comments`, { method: 'POST', body: JSON.stringify({ body: comment }) }), onSuccess: async () => { setComment(''); await refresh() } })
  const item = detail.data?.supportCase
  return <div className="page"><PageHeader eyebrow="Operations Control" title="Soporte" description="Casos operativos con ownership, lifecycle, notas internas y trazabilidad auditable." actions={can('support.manage') && <button onClick={() => setShowCreate((value) => !value)}>Nuevo caso</button>} />
    {showCreate && <section className="action-panel support-create"><label>Asunto<input value={subject} onChange={(event) => setSubject(event.target.value)} minLength={5} maxLength={200} /></label><label>Categoría<select value={category} onChange={(event) => setCategory(event.target.value)}>{['ACCOUNT', 'BOOKING', 'PAYMENT', 'PROFESSIONAL', 'SAFETY', 'OTHER'].map((value) => <option key={value}>{value}</option>)}</select></label><label>Prioridad<select value={priority} onChange={(event) => setPriority(event.target.value)}>{['LOW', 'MEDIUM', 'HIGH', 'URGENT'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="wide">Descripción<textarea value={description} onChange={(event) => setDescription(event.target.value)} minLength={10} maxLength={10000} /></label><button disabled={subject.trim().length < 5 || description.trim().length < 10 || create.isPending} onClick={() => create.mutate()}>Crear caso</button>{create.error && <p className="error" role="alert">{create.error.message}</p>}</section>}
    <SearchBar value={input} onChange={setInput} onSubmit={() => { setPage(1); setSearch(input.trim()) }} placeholder="Case key o asunto" />
    <QueryState loading={list.isLoading} error={list.error} empty={!list.data?.items.length}>{list.data && <article className="panel table-panel operations-list"><div className="table-scroll"><table><thead><tr><th>Actualizado</th><th>Caso</th><th>Categoría</th><th>Prioridad</th><th>Estado</th><th>Asignado</th><th>Actividad</th><th /></tr></thead><tbody>{list.data.items.map((row) => <tr key={row.id}><td>{dateTime(row.updatedAt)}</td><td><strong>{row.caseKey}</strong><small>{row.subject}</small></td><td>{row.category}</td><td><StatusBadge value={row.priority} /></td><td><StatusBadge value={row.status} /></td><td>{row.assignedTo ? `${row.assignedTo.firstName} ${row.assignedTo.lastName}` : 'Sin asignar'}</td><td>{row._count.comments} notas · {row._count.events} eventos</td><td><button className="table-action" onClick={() => { setSelected(row.id); setNextStatus(transitions[row.status]?.[0] || 'IN_PROGRESS'); setAssignee(row.assignedTo?.id || ''); setReason('') }}>Abrir</button></td></tr>)}</tbody></table></div><Pagination value={list.data.pagination} onChange={setPage} /></article>}</QueryState>
    {selected && <section className="panel operations-detail"><header><div><p className="eyebrow">{item?.caseKey}</p><h2>{item?.subject || 'Caso de soporte'}</h2></div><button className="secondary" onClick={() => setSelected(null)}>Cerrar</button></header><QueryState loading={detail.isLoading} error={detail.error} empty={!item}>{item && <><div className="detail-grid"><div><span>Estado</span><StatusBadge value={item.status} /></div><div><span>Prioridad</span><StatusBadge value={item.priority} /></div><div><span>Asignado</span><strong>{item.assignedTo ? `${item.assignedTo.firstName} ${item.assignedTo.lastName}` : 'Sin asignar'}</strong></div><div><span>Creado</span><strong>{dateTime(item.createdAt)}</strong></div></div><p className="support-description">{item.description}</p>{can('support.manage') && <div className="action-panel"><label>Transición<select value={nextStatus} onChange={(event) => setNextStatus(event.target.value)}>{transitions[item.status].map((value) => <option key={value}>{value}</option>)}</select></label><label>Asignación<select value={assignee} onChange={(event) => setAssignee(event.target.value)}><option value="">Sin asignar</option>{operators.data?.operators.map((operator) => <option value={operator.id} key={operator.id}>{operator.firstName} {operator.lastName}</option>)}</select></label><label>Motivo<input value={reason} onChange={(event) => setReason(event.target.value)} minLength={10} /></label><button disabled={reason.trim().length < 10 || changeStatus.isPending} onClick={() => changeStatus.mutate()}>Cambiar estado</button><button disabled={reason.trim().length < 10 || assign.isPending} onClick={() => assign.mutate()}>Asignar</button><label>Nota interna<input value={comment} onChange={(event) => setComment(event.target.value)} /></label><button disabled={!comment.trim() || addComment.isPending} onClick={() => addComment.mutate()}>Añadir nota</button>{(changeStatus.error || assign.error || addComment.error) && <p className="error" role="alert">{changeStatus.error?.message || assign.error?.message || addComment.error?.message}</p>}</div>}<div className="timeline"><h3>Historial</h3>{item.events.map((event) => <article key={event.id}><StatusBadge value={event.eventType} /><span>{event.message || `${event.fromStatus || '—'} → ${event.toStatus || '—'}`}</span><time>{dateTime(event.createdAt)}</time></article>)}{item.comments.map((entry) => <article key={entry.id}><strong>{entry.author.firstName} {entry.author.lastName}</strong><span>{entry.body}</span><time>{dateTime(entry.createdAt)}</time></article>)}</div></>}</QueryState></section>}
  </div>
}
