import React, { useEffect, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Button, Input } from '@/components/ui';
import { COLORS, SPACING, FONTS } from '@/constants/theme';
import { useAuthStore } from '@/store/authStore';
import { useTranslation } from 'react-i18next';

export default function EditProfileScreen() {
  const router=useRouter(); const {t}=useTranslation(); const {user,profile,updateProfile,isLoading}=useAuthStore();
  const [form,setForm]=useState({firstName:'',lastName:'',phone:'',address:'',city:'',state:'',postalCode:'',country:''}); const [errors,setErrors]=useState<Record<string,string>>({});
  useEffect(()=>{const u=user as any,p=profile as any;setForm({firstName:u?.firstName||'',lastName:u?.lastName||'',phone:u?.phone||'',address:p?.address||'',city:p?.city||'',state:p?.state||'',postalCode:p?.postalCode||'',country:p?.country||''});},[user,profile]);
  const set=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
  const save=async()=>{const next:Record<string,string>={};if(!form.firstName.trim())next.firstName=t('editProfile.firstNameRequired');if(!form.lastName.trim())next.lastName=t('editProfile.lastNameRequired');if(form.phone&&form.phone.replace(/\D/g,'').length<7)next.phone=t('editProfile.invalidPhone');if(form.address&&form.address.trim().length<5)next.address=t('editProfile.invalidAddress');setErrors(next);if(Object.keys(next).length)return;try{await updateProfile(Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v.trim()])));Alert.alert(t('editProfile.updated'),t('editProfile.updatedMessage'),[{text:t('common.accept'),onPress:()=>router.back()}]);}catch{Alert.alert(t('common.error'),t('editProfile.saveError'));}};
  return <SafeAreaView style={s.container}><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={26} color={COLORS.textPrimary}/></TouchableOpacity><Text style={s.title}>{t('editProfile.title')}</Text><View style={{width:26}}/></View><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.section}>{t('editProfile.personal')}</Text><Input label={t('auth.firstName')} value={form.firstName} onChangeText={v=>set('firstName',v)} autoCapitalize="words" error={errors.firstName}/><Input label={t('auth.lastName')} value={form.lastName} onChangeText={v=>set('lastName',v)} autoCapitalize="words" error={errors.lastName}/><Input label={t('auth.email')} value={(user as any)?.email||''} onChangeText={()=>{}} editable={false}/><Input label={t('auth.phone')} value={form.phone} onChangeText={v=>set('phone',v)} keyboardType="phone-pad" error={errors.phone}/><Text style={s.section}>{t('profile.address')}</Text><Input label={t('profile.address')} value={form.address} onChangeText={v=>set('address',v)} autoCapitalize="sentences" error={errors.address}/><Input label={t('common.location')} value={form.city} onChangeText={v=>set('city',v)} autoCapitalize="words"/><Input label={t('editProfile.state')} value={form.state} onChangeText={v=>set('state',v)} autoCapitalize="words"/><Input label={t('editProfile.postalCode')} value={form.postalCode} onChangeText={v=>set('postalCode',v)}/><Input label={t('editProfile.country')} value={form.country} onChangeText={v=>set('country',v)} autoCapitalize="words"/><Button title={t('common.save')} onPress={save} loading={isLoading} fullWidth/></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:COLORS.background},header:{height:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:SPACING.lg,backgroundColor:COLORS.surface,borderBottomWidth:1,borderBottomColor:COLORS.border},title:{fontSize:FONTS.sizes.lg,fontWeight:'700',color:COLORS.textPrimary},content:{padding:SPACING.lg,paddingBottom:SPACING.xxxl},section:{fontSize:FONTS.sizes.md,fontWeight:'700',color:COLORS.textPrimary,marginBottom:SPACING.md,marginTop:SPACING.sm}});
