import { useCallback, useState } from 'react'
import { Alert, Pressable, RefreshControl, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { router, useFocusEffect } from 'expo-router'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useTranslation } from 'react-i18next'
import { apiClient } from '@/services/api'
import { BORDER_RADIUS, COLORS, SPACING } from '@/constants/theme'

type Program = { key: string; name: string; rewardType: string }
type Code = { id: string; code: string; status: string; useCount: number; maxUses: number; program: { name: string } }
type Referral = { id: string; status: string; riskStatus: string; program: { name: string }; rewards: Array<{ id: string; status: string; rewardType: string; amount?: string; currency?: string; benefitKey?: string }> }

export default function ReferralsScreen() {
  const { t } = useTranslation(); const [programs, setPrograms] = useState<Program[]>([]); const [codes, setCodes] = useState<Code[]>([]); const [referrals, setReferrals] = useState<Referral[]>([]); const [claimCode, setClaimCode] = useState(''); const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { const [p, c, r] = await Promise.all([apiClient.getReferralPrograms(), apiClient.getReferralCodes(), apiClient.getMyReferrals()]); setPrograms(p.items); setCodes(c.items); setReferrals(r.items) } catch (error) { Alert.alert(t('common.error'), error instanceof Error ? error.message : t('referrals.loadError')) } finally { setLoading(false) } }, [t])
  useFocusEffect(useCallback(() => { void load() }, [load]))
  const create = async (programKey: string) => { try { await apiClient.createReferralCode(programKey); await load() } catch (error) { Alert.alert(t('common.error'), error instanceof Error ? error.message : t('referrals.actionError')) } }
  const claim = async () => { try { await apiClient.claimReferral(claimCode); setClaimCode(''); await load(); Alert.alert(t('common.success'), t('referrals.claimed')) } catch (error) { Alert.alert(t('common.error'), error instanceof Error ? error.message : t('referrals.actionError')) } }
  return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={() => router.back()}><Ionicons name="arrow-back" size={25} color={COLORS.textPrimary} /></Pressable><Text style={s.title}>{t('referrals.title')}</Text><View style={{ width: 25 }} /></View><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />}>
    <Text style={s.explain}>{t('referrals.explanation')}</Text>
    <View style={s.card}><Text style={s.cardTitle}>{t('referrals.applyCode')}</Text><TextInput accessibilityLabel={t('referrals.code')} autoCapitalize="characters" autoCorrect={false} maxLength={68} placeholder="REF_…" value={claimCode} onChangeText={setClaimCode} style={s.input} /><Pressable disabled={!/^REF_[A-Z0-9]{24,64}$/.test(claimCode.trim().toUpperCase())} style={[s.button, !claimCode && s.disabled]} onPress={claim}><Text style={s.buttonText}>{t('referrals.apply')}</Text></Pressable></View>
    <Text style={s.section}>{t('referrals.myCodes')}</Text>{codes.map((item) => <View style={s.card} key={item.id}><View style={s.row}><View style={{ flex: 1 }}><Text style={s.cardTitle}>{item.program.name}</Text><Text selectable style={s.code}>{item.code}</Text><Text style={s.meta}>{item.status} · {item.useCount}/{item.maxUses}</Text></View>{item.status === 'ACTIVE' && <Pressable accessibilityLabel={t('referrals.share')} onPress={() => Share.share({ message: `${t('referrals.shareMessage')} ${item.code}` })}><Ionicons name="share-social-outline" size={25} color={COLORS.primary} /></Pressable>}</View></View>)}
    {programs.filter((program) => !codes.some((code) => code.program.name === program.name && code.status === 'ACTIVE')).map((program) => <View style={s.card} key={program.key}><Text style={s.cardTitle}>{program.name}</Text><Text style={s.meta}>{program.rewardType}</Text><Pressable style={s.button} onPress={() => create(program.key)}><Text style={s.buttonText}>{t('referrals.createCode')}</Text></Pressable></View>)}
    <Text style={s.section}>{t('referrals.activity')}</Text>{referrals.length === 0 && <Text style={s.empty}>{t('referrals.empty')}</Text>}{referrals.map((item) => <View style={s.card} key={item.id}><View style={s.row}><Text style={s.cardTitle}>{item.program.name}</Text><Text style={s.status}>{item.status}</Text></View><Text style={s.meta}>{t('referrals.review')}: {item.riskStatus}</Text>{item.rewards.map((reward) => <Text key={reward.id} style={s.reward}>{reward.rewardType}: {reward.amount ? `${reward.amount} ${reward.currency}` : reward.benefitKey} · {reward.status}</Text>)}</View>)}
  </ScrollView></SafeAreaView>
}

const s = StyleSheet.create({ safe:{flex:1,backgroundColor:COLORS.background},header:{height:60,paddingHorizontal:SPACING.lg,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:COLORS.border},title:{fontSize:20,fontWeight:'700',color:COLORS.textPrimary},content:{padding:SPACING.lg,paddingBottom:48},explain:{color:COLORS.textSecondary,lineHeight:20,marginBottom:SPACING.lg},section:{fontWeight:'700',color:COLORS.textPrimary,fontSize:17,marginTop:SPACING.lg,marginBottom:SPACING.sm},card:{backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border,borderRadius:BORDER_RADIUS.lg,padding:SPACING.lg,marginBottom:SPACING.md},cardTitle:{fontWeight:'700',color:COLORS.textPrimary,fontSize:16},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:SPACING.md},input:{borderWidth:1,borderColor:COLORS.border,borderRadius:BORDER_RADIUS.md,padding:SPACING.md,marginVertical:SPACING.md,color:COLORS.textPrimary},button:{backgroundColor:COLORS.primary,borderRadius:BORDER_RADIUS.md,minHeight:44,alignItems:'center',justifyContent:'center',paddingHorizontal:SPACING.lg,marginTop:SPACING.md},disabled:{opacity:.45},buttonText:{color:COLORS.white,fontWeight:'700'},code:{fontFamily:'monospace',color:COLORS.primary,marginTop:SPACING.sm},meta:{color:COLORS.textSecondary,marginTop:SPACING.xs},status:{color:COLORS.primary,fontWeight:'700'},reward:{color:COLORS.textPrimary,marginTop:SPACING.sm},empty:{color:COLORS.textSecondary,paddingVertical:SPACING.lg} })
